export default {
  role: {
    module: 'রোল',
    management: 'রোল ম্যানেজমেন্ট',
    role_permissions: 'রোল পারমিশন সমূহ',
    permissions: 'পারমিশন সমূহ',
    roles: 'রোলসমূহ',
    editing: 'সম্পাদনা',

    add: 'রোল যোগ করুন',
    edit: 'রোল সম্পাদনা করুন',
    view: 'রোলের বিস্তারিত',
    delete: 'রোল মুছুন',
    info: 'রোল তথ্য',
    role_information: 'রোল তথ্য',
    role_name: 'রোলের নাম',

    loading_permissions: 'পারমিশন লোড হচ্ছে...',
    no_role_selected: 'কোনো রোল নির্বাচিত নেই',
    select_all: 'সব নির্বাচন করুন',
    no_permissions_found: 'কোনো পারমিশন পাওয়া যায়নি',
  },

  permission: {
    module: 'অনুমতি',
    management: 'অনুমতি ম্যানেজমেন্ট',
    add_by_module: 'মডিউল অনুযায়ী যোগ করুন',
    add_by_module_title: 'মডিউল অনুযায়ী অনুমতি যোগ করুন',
    edit: 'অনুমতি সম্পাদনা',
    view: 'অনুমতির বিস্তারিত',
    info: 'অনুমতির তথ্য',
    audit_info: 'অডিট তথ্য',
    slug: 'স্লাগ',
    name: 'নাম',
    permission: 'অনুমতি',

    placeholder_name: 'যেমন: Create Permission',
    placeholder_slug: 'যেমন: permission.create',
    slug_hint: 'module.action ফরম্যাট ব্যবহার করুন (যেমন: permission.create)',

    quick_module_title: 'দ্রুত মডিউল অনুমতি',
    quick_module_help:
      'একটি মডিউল নাম লিখুন (যেমন: country) এবং স্বয়ংক্রিয়ভাবে create / edit / view / delete অনুমতি তৈরি হবে।',
    module_name: 'মডিউলের নাম',
    display_label: 'প্রদর্শন লেবেল (ঐচ্ছিক)',
    display_label_hint: 'অনুমতির নামে ব্যবহৃত হয়। খালি রাখলে মডিউল নাম ব্যবহার হবে।',
    actions: 'অ্যাকশন',
    extra_actions: 'অতিরিক্ত অ্যাকশন (ঐচ্ছিক)',
    extra_actions_hint: 'কমা দিয়ে আলাদা করুন। উদাহরণ: export, view_summary',
    placeholder_module: 'যেমন: country, agent, flight_summary',
    placeholder_label: 'যেমন: Country',
    placeholder_extra_actions: 'যেমন: export, view_summary, collect',
    assign_to_admin: 'এই অনুমতিগুলো Admin রোলেও যোগ করুন',
    preview: 'প্রিভিউ ({count})',
    create_count: '{count}টি অনুমতি তৈরি করুন',
    creating: 'তৈরি হচ্ছে...',

    bulk_delete_confirm: 'নির্বাচিত রেকর্ডগুলো মুছে ফেলতে চান?',
    operation_successful: 'অনুমতি অপারেশন সফল হয়েছে',
    request_failed: 'অনুরোধ ব্যর্থ: {message}',
    unknown_error: 'অজানা ত্রুটি',
    created_count: '{created}টি অনুমতি তৈরি হয়েছে',
    created_with_skipped: '{created}টি অনুমতি তৈরি হয়েছে ({skipped}টি আগে থেকেই ছিল)',
    all_exist: 'নির্বাচিত সব অনুমতি আগে থেকেই আছে ({skipped})',
  },
}
