export default {
  role: {
    module: 'Role',
    management: 'Role Management',
    role_permissions: 'Role Permissions',
    permissions: 'Permissions',
    roles: 'Roles',
    editing: 'Editing',

    add: 'Add Role',
    edit: 'Edit Role',
    view: 'View Role Details',
    delete: 'Delete Role',
    info: 'Role Info',
    role_information: 'Role Information',
    role_name: 'Role Name',

    loading_permissions: 'Loading permissions...',
    no_role_selected: 'No role selected',
    select_all: 'Select All',
    no_permissions_found: 'No permissions found',
  },

  permission: {
    module: 'Permission',
    management: 'Permission Management',
    add_by_module: 'Add by Module',
    add_by_module_title: 'Add Permissions by Module',
    edit: 'Edit Permission',
    view: 'View Permission Details',
    info: 'Permission Info',
    audit_info: 'Audit Info',
    slug: 'Slug',
    name: 'Name',
    permission: 'Permission',

    placeholder_name: 'Eg: Create Permission',
    placeholder_slug: 'Eg: permission.create',
    slug_hint: 'Use module.action format (e.g. permission.create)',

    quick_module_title: 'Quick Module Permissions',
    quick_module_help:
      'Enter a module name (e.g. country) and we will auto-create create / edit / view / delete permissions.',
    module_name: 'Module Name',
    display_label: 'Display Label (optional)',
    display_label_hint: 'Used in permission names. Leave empty to use the module name.',
    actions: 'Actions',
    extra_actions: 'Extra Actions (optional)',
    extra_actions_hint: 'Comma-separated. Example: export, view_summary',
    placeholder_module: 'Eg: country, agent, flight_summary',
    placeholder_label: 'Eg: Country',
    placeholder_extra_actions: 'Eg: export, view_summary, collect',
    assign_to_admin: 'Also assign these permissions to Admin role',
    preview: 'Preview ({count})',
    create_count: 'Create {count} Permissions',
    creating: 'Creating...',

    bulk_delete_confirm: 'Are you sure to delete selected records?',
    operation_successful: 'Permission operation successful',
    request_failed: 'Request Failed: {message}',
    unknown_error: 'Unknown error',
    created_count: 'Created {created} permissions',
    created_with_skipped: 'Created {created} permissions ({skipped} already existed)',
    all_exist: 'All selected permissions already exist ({skipped})',
  },
}
