<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ATS Summary Report</title>
</head>
<body style="margin:0;padding:0;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif;">

    <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:30px 0;">
        <tr>
            <td align="center">

                <table width="650" cellpadding="0" cellspacing="0"
                    style="background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e7eb;">

                    <!-- Header -->
                    <tr>
                        <td style="background:#2563eb;padding:25px 30px;">
                            <h2 style="margin:0;color:#ffffff;font-size:24px;">
                                ATS Summary Report
                            </h2>

                            <p style="margin:8px 0 0;color:#dbeafe;font-size:13px;">
                                ATS Process Overview & Application Statistics
                            </p>
                        </td>
                    </tr>

                    <!-- Body -->
                    <tr>
                        <td style="padding:35px 30px;">

                            <p style="margin:0 0 20px;font-size:15px;color:#374151;">
                                Dear Team,
                            </p>

                            <p style="margin:0 0 20px;font-size:14px;line-height:24px;color:#4b5563;">
                                Please find attached the latest ATS Summary Report containing
                                process-wise application statistics across all active jobs.
                            </p>

                            <!-- Stats Card -->
                            <table width="100%" cellpadding="0" cellspacing="0" style="margin:25px 0;">
                                <tr>
                                    <td style="background:#eff6ff;border:1px solid #dbeafe;border-radius:6px;padding:20px;">

                                        <div style="font-size:12px;color:#6b7280;text-transform:uppercase;font-weight:bold;">
                                            Total Active Applications
                                        </div>

                                        <div style="font-size:32px;font-weight:bold;color:#111827;margin-top:8px;">
                                            {{ number_format($grandTotal ?? 0) }}
                                        </div>

                                    </td>
                                </tr>
                            </table>

                            <p style="margin:0 0 15px;font-size:14px;line-height:24px;color:#4b5563;">
                                The detailed ATS Summary Report has been attached as a PDF document
                                for your review.
                            </p>

                            <p style="margin:0;font-size:14px;line-height:24px;color:#4b5563;">
                                This report includes job-wise ATS process counts, overall process
                                statistics, and active application summaries.
                            </p>

                        </td>
                    </tr>

                    <!-- Footer -->
                    <tr>
                        <td style="background:#f9fafb;padding:25px 30px;border-top:1px solid #e5e7eb;">

                            <p style="margin:0 0 8px;font-size:14px;color:#111827;">
                                Regards,
                            </p>

                            <p style="margin:0;font-weight:bold;color:#111827;">
                                {{ $settings['company_name'] ?? 'ATS Team' }}
                            </p>

                            <p style="margin:15px 0 0;font-size:12px;color:#9ca3af;">
                                This is an automated email generated by the
                                {{ $settings['software_name'] ?? 'ATS System' }}.
                                Please do not reply directly to this message.
                            </p>

                        </td>
                    </tr>

                </table>

            </td>
        </tr>
    </table>

</body>
</html>
