<template>
  <Teleport to="body">
    <Transition name="gp-preview">
      <div
        v-if="isVisible"
        class="fixed inset-0 z-[90] flex items-stretch justify-center bg-slate-950/75"
        role="dialog"
        aria-modal="true"
        aria-labelledby="gross-profit-preview-title"
      >
        <div
          class="gp-preview-panel flex h-full w-full max-w-none flex-col overflow-hidden bg-white shadow-2xl"
        >
          <header
            class="flex shrink-0 items-center justify-between gap-3 border-b border-slate-200 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 px-4 py-3 text-white sm:px-6"
          >
            <div class="min-w-0">
              <p class="text-[11px] font-semibold uppercase tracking-[0.18em] text-emerald-300">
                Finance Report
              </p>
              <h2 id="gross-profit-preview-title" class="truncate text-lg font-semibold sm:text-xl">
                Gross Profit Report
              </h2>
              <p class="mt-0.5 truncate text-xs text-slate-300">
                {{ filename || 'Backend PDF preview' }}
              </p>
            </div>

            <div class="flex shrink-0 items-center gap-2">
              <button
                type="button"
                class="inline-flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-sm font-medium text-white ring-1 ring-white/15 transition hover:bg-white/20 disabled:cursor-not-allowed disabled:opacity-50"
                :disabled="!pdfUrl || loading"
                @click="$emit('download')"
              >
                <i class="fa fa-download"></i>
                <span class="hidden sm:inline">Download</span>
              </button>
              <button
                type="button"
                class="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-sm font-medium text-white transition hover:bg-emerald-400 disabled:cursor-not-allowed disabled:opacity-50"
                :disabled="!pdfUrl || loading"
                @click="$emit('print')"
              >
                <i class="fa fa-print"></i>
                <span class="hidden sm:inline">Print</span>
              </button>
              <button
                type="button"
                class="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-white/10 text-xl text-white ring-1 ring-white/15 transition hover:bg-red-500/80"
                aria-label="Close preview"
                @click="close"
              >
                &times;
              </button>
            </div>
          </header>

          <div class="relative min-h-0 flex-1 bg-slate-200">
            <div
              v-if="loading"
              class="absolute inset-0 z-10 flex flex-col items-center justify-center gap-4 bg-slate-50"
            >
              <div
                class="flex h-16 w-16 items-center justify-center rounded-2xl bg-red-600 text-white shadow-lg"
              >
                <i class="fa fa-file-pdf-o text-2xl"></i>
              </div>
              <div class="text-center">
                <p class="text-base font-semibold text-slate-900">Preparing report preview</p>
                <p class="mt-1 text-sm text-slate-500">Fetching the PDF generated by the server…</p>
              </div>
              <div class="h-1.5 w-48 overflow-hidden rounded-full bg-slate-200">
                <div class="h-full w-1/2 animate-pulse rounded-full bg-emerald-500"></div>
              </div>
            </div>

            <div
              v-else-if="error"
              class="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3 px-6 text-center"
            >
              <div
                class="flex h-14 w-14 items-center justify-center rounded-full bg-red-50 text-red-600"
              >
                <i class="fa fa-exclamation-triangle text-xl"></i>
              </div>
              <p class="text-base font-semibold text-slate-900">Unable to load PDF preview</p>
              <p class="max-w-md text-sm text-slate-500">{{ error }}</p>
              <button
                type="button"
                class="mt-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800"
                @click="$emit('retry')"
              >
                Try again
              </button>
            </div>

            <iframe
              v-else-if="pdfUrl"
              :src="iframeSrc"
              class="h-full w-full border-0 bg-slate-200"
              title="Gross Profit Report PDF"
            ></iframe>
          </div>

          <footer
            class="flex shrink-0 items-center justify-between border-t border-slate-200 bg-slate-50 px-4 py-2 text-xs text-slate-500 sm:px-6"
          >
            <span>Official gross profit statement generated from current filters.</span>
            <span class="hidden sm:inline">Press Esc to close</span>
          </footer>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
import { computed, onMounted, onUnmounted, watch } from 'vue'

const props = defineProps({
  isVisible: { type: Boolean, default: false },
  loading: { type: Boolean, default: false },
  error: { type: String, default: '' },
  pdfUrl: { type: String, default: '' },
  filename: { type: String, default: '' },
})

const emit = defineEmits(['close', 'download', 'print', 'retry'])

const iframeSrc = computed(() =>
  props.pdfUrl ? `${props.pdfUrl}#toolbar=1&navpanes=0` : ''
)

function close() {
  emit('close')
}

function onKeydown(event) {
  if (event.key === 'Escape' && props.isVisible) {
    close()
  }
}

watch(
  () => props.isVisible,
  (visible) => {
    document.body.style.overflow = visible ? 'hidden' : ''
  }
)

onMounted(() => {
  window.addEventListener('keydown', onKeydown)
})

onUnmounted(() => {
  window.removeEventListener('keydown', onKeydown)
  document.body.style.overflow = ''
})
</script>

<style scoped>
.gp-preview-enter-active,
.gp-preview-leave-active {
  transition: opacity 0.2s ease;
}

.gp-preview-enter-active .gp-preview-panel,
.gp-preview-leave-active .gp-preview-panel {
  transition: transform 0.22s ease;
}

.gp-preview-enter-from,
.gp-preview-leave-to {
  opacity: 0;
}

.gp-preview-enter-from .gp-preview-panel,
.gp-preview-leave-to .gp-preview-panel {
  transform: translateY(10px);
}
</style>
