export default {
  journals: {
    module: 'জার্নাল',
    management: 'জার্নাল ব্যবস্থাপনা',
    sheet_title: 'জার্নাল এন্ট্রি',
    je_no: 'জেই নং',
    date: 'তারিখ',
    transaction: 'লেনদেন / টেস্ট কেস',
    account_code: 'অ্যাকাউন্ট কোড',
    account_name: 'অ্যাকাউন্টের নাম',
    party_ref: 'পার্টি / রেফ',
    debit: 'ডেবিট (BDT)',
    credit: 'ক্রেডিট (BDT)',
    cost_class: 'কস্ট ক্লাস',
    project_client: 'জব / ডিমান্ড লেটার',
    static_note: 'সিস্টেম থেকে পোস্ট করা জার্নাল দেখানো হচ্ছে',
    empty_note: 'এখনো কোনো জার্নাল নেই। পোস্ট করলে এখানে দেখা যাবে।',
    loading: 'জার্নাল লোড হচ্ছে...',

    post_title: 'জার্নাল পোস্ট',
    post_static_note: 'জার্নাল তথ্য ও লাইন পূরণ করে লেজারে পোস্ট করুন।',
    tab_bill_entry: 'বিল এন্ট্রি',
    tab_approval: 'অনুমোদন',
    tab_payment: 'পেমেন্ট',
    approval_tab_placeholder: 'অনুমোদন ওয়ার্কফ্লো কন্টেন্ট এখানে দেখা যাবে।',
    payment_tab_placeholder: 'পেমেন্ট কন্টেন্ট এখানে দেখা যাবে।',
    approval_select_title: 'অনুমোদনের অপেক্ষায় থাকা জার্নাল',
    approval_select_hint: 'রিড-ওনলি প্রিভিউ দেখতে একটি সাবমিট করা জার্নাল নির্বাচন করুন।',
    select_pending_journal: 'পেন্ডিং জার্নাল',
    search_pending_journal: 'ভাউচার, পার্টি বা রেফারেন্স দিয়ে খুঁজুন',
    loading_pending_journals: 'পেন্ডিং জার্নাল লোড হচ্ছে...',
    no_pending_journals: 'অনুমোদনের অপেক্ষায় কোনো জার্নাল নেই',
    no_pending_journals_hint: 'বিল এন্ট্রি ট্যাব থেকে অনুমোদনের জন্য জার্নাল সাবমিট করুন।',
    select_journal_to_preview: 'প্রিভিউ দেখতে একটি জার্নাল নির্বাচন করুন',
    select_journal_to_preview_hint: 'উপরের সার্চ থেকে একটি অপেক্ষমাণ জার্নাল বেছে নিন।',
    waiting_for_approval: 'অনুমোদনের অপেক্ষায়',
    approved: 'অনুমোদিত',
    balance: 'ব্যালান্স',
    lines_count: 'লাইন',
    submitted_at: 'সাবমিটের সময়',
    manager_comment: 'ম্যানেজার মন্তব্য',
    manager_comment_placeholder: 'পেমেন্ট টিমের জন্য অনুমোদন মন্তব্য লিখুন...',
    approve_journal: 'অনুমোদন',
    approving: 'অনুমোদন হচ্ছে...',
    clear_selection: 'নির্বাচন মুছুন',
    approved_success: 'জার্নাল {voucher} সফলভাবে অনুমোদিত হয়েছে।',
    error_manager_comment_required: 'অনুমোদনের আগে ম্যানেজার মন্তব্য লিখুন।',
    payment_select_title: 'পেমেন্টের জন্য প্রস্তুত অনুমোদিত জার্নাল',
    payment_select_hint: 'একটি অনুমোদিত জার্নাল নির্বাচন করুন, প্রয়োজনে সম্পাদনা করে পে করুন।',
    select_approved_journal: 'অনুমোদিত জার্নাল',
    search_approved_journal: 'ভাউচার, পার্টি বা রেফারেন্স দিয়ে খুঁজুন',
    loading_approved_journals: 'অনুমোদিত জার্নাল লোড হচ্ছে...',
    no_approved_journals: 'পেমেন্টের জন্য কোনো অনুমোদিত জার্নাল নেই',
    no_approved_journals_hint: 'আগে অনুমোদন ট্যাব থেকে একটি জার্নাল অনুমোদন করুন।',
    select_journal_to_pay: 'পে করতে একটি জার্নাল নির্বাচন করুন',
    select_journal_to_pay_hint: 'উপরের সার্চ থেকে একটি অনুমোদিত জার্নাল বেছে নিন।',
    pay_journal: 'পে',
    paying: 'পে হচ্ছে...',
    paid_success: 'জার্নাল {voucher} পে ও পোস্ট হয়েছে।',
    back_to_list: 'জার্নাল তালিকায় ফিরে যান',
    voucher_no: 'ভাউচার নং',
    status: 'স্ট্যাটাস',
    total_debit: 'মোট ডেবিট',
    total_credit: 'মোট ক্রেডিট',
    journal_information: 'জার্নাল তথ্য',
    voucher_date: 'ভাউচার তারিখ',
    transaction_type: 'লেনদেনের ধরন',
    select_transaction_type: 'লেনদেনের ধরন খুঁজুন',
    reference_no: 'রেফারেন্স নং',
    reference_no_placeholder: 'রেফারেন্স নং লিখুন',
    party_type: 'পার্টির ধরন',
    select_party_type: 'পার্টির ধরন খুঁজুন',
    party_ledger: 'পার্টি / লেজার',
    select_party: 'কোড বা নাম দিয়ে পার্টি খুঁজুন',
    loading_parties: 'পার্টি লোড হচ্ছে...',
    project_client_demand: 'জব / ডিমান্ড লেটার',
    tab_jobs: 'জব',
    tab_demand_letters: 'ডিমান্ড লেটার',
    select_project: 'জব / ডিমান্ড লেটার খুঁজুন',
    select_demand_letter: 'ডিমান্ড লেটার খুঁজুন',
    loading_jobs: 'জব লোড হচ্ছে...',
    loading_demand_letters: 'ডিমান্ড লেটার লোড হচ্ছে...',
    no_jobs_found: 'কোনো জব পাওয়া যায়নি',
    no_demand_letters_found: 'কোনো ডিমান্ড লেটার পাওয়া যায়নি',
    journal_lines: 'জার্নাল লাইন',
    balance_hint: 'পোস্ট করার আগে ডেবিট ও ক্রেডিট সমান হতে হবে।',
    add_line: 'লাইন যোগ করুন',
    account: 'অ্যাকাউন্ট',
    select_account: 'কোড বা নাম দিয়ে অ্যাকাউন্ট খুঁজুন',
    loading_accounts: 'অ্যাকাউন্ট লোড হচ্ছে...',
    sub_ledger: 'সাব-লেজার / পার্টি',
    cost_revenue_type: 'কস্ট / রেভিনিউ টাইপ',
    select_cost_type: 'টাইপ নির্বাচন করুন',
    debit_label: 'ডেবিট',
    credit_label: 'ক্রেডিট',
    action: 'অ্যাকশন',
    optional: 'ঐচ্ছিক',
    edit: 'এডিট',
    copy: 'কপি',
    ledger: 'লেজার',
    delete: 'ডিলিট',
    total: 'মোট',
    difference: 'পার্থক্য',
    balanced: 'ব্যালান্সড',
    unbalanced: 'আনব্যালান্সড',
    narration: 'ন্যারেশন',
    narration_placeholder:
      'উদাহরণ: ফেরত আসা ক্যান্ডিডেটকে লাম্প-সাম রিক্রুটমেন্ট সার্ভিস চার্জ রিফান্ড',
    receipt: 'রসিদ',
    receipts: 'রসিদসমূহ',
    receipt_optional: 'রসিদ (ঐচ্ছিক)',
    receipt_hint: 'JPG বা PNG, প্রতিটি সর্বোচ্চ ২ MB · সর্বোচ্চ ১০টি ছবি',
    receipt_max_files: 'আপনি সর্বোচ্চ {max}টি ছবি আপলোড করতে পারেন।',
    receipt_invalid_type: 'শুধু JPG বা PNG ছবি অনুমোদিত।',
    receipt_file_too_large: 'প্রতিটি ছবি ২ MB-এর কম হতে হবে। "{name}" খুব বড়।',
    receipt_extra_skipped: 'সর্বোচ্চ {max}টি ছবি অনুমোদিত। অতিরিক্ত ফাইল বাদ দেওয়া হয়েছে।',
    receipt_preview: 'রসিদ প্রিভিউ',
    receipt_click_to_preview: 'প্রিভিউ দেখতে ক্লিক করুন',
    receipt_download: 'ডাউনলোড',
    receipt_previous: 'আগের রসিদ',
    receipt_next: 'পরের রসিদ',
    close: 'বন্ধ',
    posting_preview: 'পোস্টিং প্রিভিউ',
    posting_preview_empty: 'এখনো কোনো জার্নাল লাইন দেওয়া হয়নি',
    prepared_by: 'প্রস্তুতকারী',
    current_user: 'বর্তমান ব্যবহারকারী',
    approval: 'অনুমোদন',
    manager_required: 'ম্যানেজার প্রয়োজন',
    save_draft: 'ড্রাফট সেভ',
    submit_approval: 'অনুমোদনের জন্য সাবমিট',
    post_journal: 'জার্নাল পোস্ট',
    posting: 'পোস্ট হচ্ছে...',
    submitting: 'সাবমিট হচ্ছে...',
    posted_success: 'জার্নাল {voucher} সফলভাবে পোস্ট হয়েছে।',
    submitted_success: 'জার্নাল {voucher} অনুমোদনের জন্য সাবমিট হয়েছে।',
    error_voucher_date_required: 'ভাউচার তারিখ নির্বাচন করুন।',
    error_transaction_type_required: 'লেনদেনের ধরন নির্বাচন করুন।',
    error_min_lines: 'অ্যাকাউন্ট ও পরিমাণসহ কমপক্ষে দুটি জার্নাল লাইন দিন।',
    error_empty_row: 'সারি {row} খালি। পোস্ট করার আগে পূরণ করুন বা মুছে দিন।',
    error_empty_rows: 'সারি {rows} খালি। পোস্ট করার আগে পূরণ করুন বা মুছে দিন।',
    error_row_account_required: 'সারি {row}: একটি অ্যাকাউন্ট নির্বাচন করুন।',
    error_row_amount_required: 'সারি {row}: ডেবিট বা ক্রেডিট পরিমাণ দিন।',
    error_row_both_amounts: 'সারি {row}: একই লাইনে ডেবিট ও ক্রেডিট দুটোই দেওয়া যাবে না।',
    error_unbalanced: 'পোস্ট করার আগে ডেবিট ও ক্রেডিট সমান হতে হবে।',
    dr: 'ডেবিট',
    cr: 'ক্রেডিট',
  },
  journal_transaction_types: {
    module: 'লেনদেনের ধরন',
    management: 'লেনদেনের ধরন ব্যবস্থাপনা',
    add: 'লেনদেনের ধরন যোগ করুন',
    edit: 'লেনদেনের ধরন সম্পাদনা',
    view: 'লেনদেনের ধরন দেখুন',
    information: 'লেনদেনের ধরন তথ্য',
    code: 'কোড',
    name: 'নাম',
    sort_order: 'ক্রম',
  },
}
