export default {
  journals: {
    module: 'জার্নাল',
    management: 'জার্নাল ব্যবস্থাপনা',
    sheet_title: 'ERP Test Journal – Comprehensive Sample Transactions',
    je_no: 'জেই নং',
    date: 'তারিখ',
    transaction: 'লেনদেন / টেস্ট কেস',
    account_code: 'অ্যাকাউন্ট কোড',
    account_name: 'অ্যাকাউন্টের নাম',
    party_ref: 'পার্টি / রেফ',
    debit: 'ডেবিট (BDT)',
    credit: 'ক্রেডিট (BDT)',
    cost_class: 'কস্ট ক্লাস',
    project_client: 'প্রজেক্ট / ক্লায়েন্ট',
    static_note: 'নমুনা স্ট্যাটিক ডেটা দেখানো হচ্ছে (শুধুমাত্র ফ্রন্টএন্ড)',

    post_title: 'জার্নাল পোস্ট',
    post_static_note: 'শুধুমাত্র স্ট্যাটিক ফর্ম UI — এখনো API সেভ/পোস্ট নেই',
    back_to_list: 'জার্নাল তালিকায় ফিরে যান',
    voucher_no: 'ভাউচার নং',
    status: 'স্ট্যাটাস',
    total_debit: 'মোট ডেবিট',
    total_credit: 'মোট ক্রেডিট',
    journal_information: 'জার্নাল তথ্য',
    voucher_date: 'ভাউচার তারিখ',
    transaction_type: 'লেনদেনের ধরন',
    reference_no: 'রেফারেন্স নং',
    party_type: 'পার্টির ধরন',
    party_ledger: 'পার্টি / লেজার',
    select_party: 'কোড বা নাম দিয়ে পার্টি খুঁজুন',
    loading_parties: 'পার্টি লোড হচ্ছে...',
    project_client_demand: 'প্রজেক্ট / ক্লায়েন্ট / ডিমান্ড',
    journal_lines: 'জার্নাল লাইন',
    balance_hint: 'পোস্ট করার আগে ডেবিট ও ক্রেডিট সমান হতে হবে।',
    add_line: 'লাইন যোগ করুন',
    account: 'অ্যাকাউন্ট',
    select_account: 'কোড বা নাম দিয়ে অ্যাকাউন্ট খুঁজুন',
    loading_accounts: 'অ্যাকাউন্ট লোড হচ্ছে...',
    sub_ledger: 'সাব-লেজার / পার্টি',
    cost_revenue_type: 'কস্ট / রেভিনিউ টাইপ',
    debit_label: 'ডেবিট',
    credit_label: 'ক্রেডিট',
    action: 'অ্যাকশন',
    optional: 'ঐচ্ছিক',
    edit: 'এডিট',
    copy: 'কপি',
    ledger: 'লেজার',
    delete: 'ডিলিট',
    total: 'মোট',
    difference: 'পার্থক্য',
    balanced: 'ব্যালান্সড',
    unbalanced: 'আনব্যালান্সড',
    narration: 'ন্যারেশন',
    narration_placeholder:
      'উদাহরণ: ফেরত আসা ক্যান্ডিডেটকে লাম্প-সাম রিক্রুটমেন্ট সার্ভিস চার্জ রিফান্ড',
    posting_preview: 'পোস্টিং প্রিভিউ',
    prepared_by: 'প্রস্তুতকারী',
    current_user: 'বর্তমান ব্যবহারকারী',
    approval: 'অনুমোদন',
    manager_required: 'ম্যানেজার প্রয়োজন',
    save_draft: 'ড্রাফট সেভ',
    submit_approval: 'অনুমোদনের জন্য সাবমিট',
    post_journal: 'জার্নাল পোস্ট',
    dr: 'ডেবিট',
    cr: 'ক্রেডিট',
  },
}
