export default {
  journals: {
    module: 'জার্নাল',
    management: 'জার্নাল ব্যবস্থাপনা',
    sheet_title: 'জার্নাল এন্ট্রি',
    je_no: 'জেই নং',
    date: 'তারিখ',
    transaction: 'লেনদেন / টেস্ট কেস',
    account_code: 'অ্যাকাউন্ট কোড',
    account_name: 'অ্যাকাউন্টের নাম',
    party_ref: 'পার্টি / রেফ',
    debit: 'ডেবিট (BDT)',
    credit: 'ক্রেডিট (BDT)',
    cost_class: 'কস্ট ক্লাস',
    project_client: 'জব / ডিমান্ড লেটার',
    static_note: 'সিস্টেম থেকে পোস্ট করা জার্নাল দেখানো হচ্ছে',
    empty_note: 'এখনো কোনো জার্নাল নেই। পোস্ট করলে এখানে দেখা যাবে।',
    loading: 'জার্নাল লোড হচ্ছে...',

    post_title: 'জার্নাল পোস্ট',
    post_static_note: 'জার্নাল তথ্য ও লাইন পূরণ করে লেজারে পোস্ট করুন।',
    tab_bill_entry: 'বিল এন্ট্রি',
    tab_approval: 'অনুমোদন',
    tab_payment: 'পেমেন্ট',
    approval_tab_placeholder: 'অনুমোদন ওয়ার্কফ্লো কন্টেন্ট এখানে দেখা যাবে।',
    payment_tab_placeholder: 'পেমেন্ট কন্টেন্ট এখানে দেখা যাবে।',
    approval_select_title: 'অনুমোদনের অপেক্ষায় থাকা জার্নাল',
    approval_select_hint: 'রিড-ওনলি প্রিভিউ দেখতে একটি সাবমিট করা জার্নাল নির্বাচন করুন।',
    select_pending_journal: 'পেন্ডিং জার্নাল',
    search_pending_journal: 'ভাউচার, পার্টি বা রেফারেন্স দিয়ে খুঁজুন',
    loading_pending_journals: 'পেন্ডিং জার্নাল লোড হচ্ছে...',
    no_pending_journals: 'অনুমোদনের অপেক্ষায় কোনো জার্নাল নেই',
    no_pending_journals_hint: 'বিল এন্ট্রি ট্যাব থেকে অনুমোদনের জন্য জার্নাল সাবমিট করুন।',
    select_journal_to_preview: 'প্রিভিউ দেখতে একটি জার্নাল নির্বাচন করুন',
    select_journal_to_preview_hint: 'উপরের সার্চ থেকে একটি অপেক্ষমাণ জার্নাল বেছে নিন।',
    waiting_for_approval: 'অনুমোদনের অপেক্ষায়',
    approved: 'অনুমোদিত',
    balance: 'ব্যালান্স',
    lines_count: 'লাইন',
    submitted_at: 'সাবমিটের সময়',
    manager_comment: 'ম্যানেজার মন্তব্য',
    manager_comment_placeholder: 'পেমেন্ট টিমের জন্য অনুমোদন মন্তব্য লিখুন...',
    approve_journal: 'অনুমোদন',
    approving: 'অনুমোদন হচ্ছে...',
    clear_selection: 'নির্বাচন মুছুন',
    approved_success: 'জার্নাল {voucher} সফলভাবে অনুমোদিত হয়েছে।',
    error_manager_comment_required: 'অনুমোদনের আগে ম্যানেজার মন্তব্য লিখুন।',
    error_return_comment_required: 'ফেরত পাঠানোর আগে রিটার্ন মন্তব্য লিখুন।',
    manager_action_hint: 'অনুমোদন বা হিসাবরক্ষকের কাছে ফেরত পাঠাতে মন্তব্য লিখুন।',
    manager_action_placeholder: 'কী সংশোধন করতে হবে তা ব্যাখ্যা করুন, অথবা অনুমোদনের নোট লিখুন...',
    manager_comment_presets_approve: 'দ্রুত অনুমোদন মন্তব্য',
    manager_comment_presets_return: 'দ্রুত ফেরত মন্তব্য',
    preset_approve_payment_label: 'পেমেন্টে এগিয়ে যান',
    preset_approve_payment_text: 'অনুমোদিত। পেমেন্ট প্রক্রিয়াকরণে এগিয়ে যান।',
    preset_approve_verified_label: 'পরিমাণ যাচাই হয়েছে',
    preset_approve_verified_text: 'অ্যাকাউন্ট ও পরিমাণ যাচাই করা হয়েছে। পেমেন্টের জন্য অনুমোদিত।',
    preset_approve_documentation_label: 'ডকুমেন্ট সম্পূর্ণ',
    preset_approve_documentation_text: 'ডকুমেন্টেশন সম্পূর্ণ। অনুমোদিত।',
    preset_approve_policy_label: 'নীতি অনুযায়ী',
    preset_approve_policy_text: 'কোম্পানির নীতি অনুযায়ী অনুমোদিত।',
    preset_return_amounts_label: 'পরিমাণ ঠিক করুন',
    preset_return_amounts_text: 'ডেবিট/ক্রেডিট পরিমাণ সংশোধন করে পুনরায় জমা দিন।',
    preset_return_party_label: 'পার্টি লেজার ঠিক করুন',
    preset_return_party_text: 'পার্টি লেজার নির্বাচন সঠিক নয়। আপডেট করে পুনরায় জমা দিন।',
    preset_return_receipt_label: 'রসিদ নেই',
    preset_return_receipt_text: 'সাপোর্টিং রসিদ বা ডকুমেন্ট নেই। সংযুক্ত করে পুনরায় জমা দিন।',
    preset_return_narration_label: 'ন্যারেশন স্পষ্ট করুন',
    preset_return_narration_text: 'ন্যারেশন স্পষ্ট নয়। সঠিক বিবরণ যোগ করে পুনরায় জমা দিন।',
    preset_return_account_label: 'অ্যাকাউন্ট ঠিক করুন',
    preset_return_account_text: 'অ্যাকাউন্ট ম্যাপিং সংশোধন প্রয়োজন। চার্ট অফ অ্যাকাউন্টস পর্যালোচনা করে পুনরায় জমা দিন।',
    return_journal: 'ফেরত',
    returning: 'ফেরত পাঠানো হচ্ছে...',
    returned: 'ফেরত',
    returned_success: 'জার্নাল {voucher} বিল এন্ট্রিতে ফেরত পাঠানো হয়েছে।',
    returned_select_title: 'ফেরত জার্নাল',
    returned_select_hint: 'আপডেট ও পুনরায় অনুমোদনের জন্য একটি ফেরত জার্নাল নির্বাচন করুন।',
    select_returned_journal: 'ফেরত জার্নাল',
    search_returned_journal: 'ভাউচার, পার্টি বা রেফারেন্স দিয়ে খুঁজুন',
    loading_returned_journals: 'ফেরত জার্নাল লোড হচ্ছে...',
    no_returned_journals: 'কোনো ফেরত জার্নাল নেই',
    manager_return_comment: 'ম্যানেজারের ফেরত মন্তব্য',
    manager_return_comment_hint: 'এই মন্তব্য অনুযায়ী জার্নাল আপডেট করে পুনরায় অনুমোদনের জন্য জমা দিন।',
    resubmit_approval: 'পুনরায় অনুমোদনের জন্য জমা দিন',
    resubmitting: 'পুনরায় জমা হচ্ছে...',
    resubmitted_success: 'জার্নাল {voucher} পুনরায় অনুমোদনের জন্য জমা হয়েছে।',
    success_kicker_submitted: 'বিল এন্ট্রি সম্পন্ন',
    success_kicker_resubmitted: 'পুনরায় জমা',
    success_kicker_posted: 'পোস্ট হয়েছে',
    success_title_submitted: 'অনুমোদনের জন্য জমা হয়েছে',
    success_title_resubmitted: 'পুনরায় অনুমোদনের জন্য জমা',
    success_title_posted: 'জার্নাল সফলভাবে পোস্ট হয়েছে',
    success_message_submitted: 'জার্নাল {voucher} সংরক্ষিত হয়েছে এবং ম্যানেজারের অনুমোদনের জন্য পাঠানো হয়েছে।',
    success_message_resubmitted: 'জার্নাল {voucher} আপডেট হয়েছে এবং পুনরায় অনুমোদনের জন্য পাঠানো হয়েছে।',
    success_message_posted: 'জার্নাল {voucher} লেজারে পোস্ট হয়েছে।',
    success_go_to_approval: 'অনুমোদনে যান',
    success_view_journals: 'জার্নাল দেখুন',
    success_create_new: 'নতুন এন্ট্রি তৈরি করুন',
    approval_success_kicker: 'অনুমোদন সম্পন্ন',
    approval_success_title: 'জার্নাল অনুমোদিত',
    approval_success_message: 'জার্নাল {voucher} অনুমোদিত হয়েছে এবং পেমেন্টের জন্য প্রস্তুত।',
    approval_success_go_to_payment: 'পেমেন্টে যান',
    approval_success_review_more: 'আরও অনুমোদন দেখুন',
    return_success_kicker: 'ফেরত সম্পন্ন',
    return_success_title: 'জার্নাল ফেরত পাঠানো হয়েছে',
    return_success_message:
      'জার্নাল {voucher} আপডেটের জন্য বিল এন্ট্রিতে ফেরত পাঠানো হয়েছে।',
    return_success_go_to_bill_entry: 'বিল এন্ট্রিতে যান',
    return_success_review_more: 'আরও অনুমোদন দেখুন',
    payment_select_title: 'পেমেন্টের জন্য প্রস্তুত অনুমোদিত জার্নাল',
    payment_select_hint: 'একটি অনুমোদিত জার্নাল নির্বাচন করুন, প্রয়োজনে সম্পাদনা করে পে করুন।',
    select_approved_journal: 'অনুমোদিত জার্নাল',
    search_approved_journal: 'ভাউচার, পার্টি বা রেফারেন্স দিয়ে খুঁজুন',
    loading_approved_journals: 'অনুমোদিত জার্নাল লোড হচ্ছে...',
    no_approved_journals: 'পেমেন্টের জন্য কোনো অনুমোদিত জার্নাল নেই',
    no_approved_journals_hint: 'আগে অনুমোদন ট্যাব থেকে একটি জার্নাল অনুমোদন করুন।',
    select_journal_to_pay: 'পে করতে একটি জার্নাল নির্বাচন করুন',
    select_journal_to_pay_hint: 'উপরের সার্চ থেকে একটি অনুমোদিত জার্নাল বেছে নিন।',
    pay_journal: 'পে',
    paying: 'পে হচ্ছে...',
    paid_success: 'জার্নাল {voucher} পে ও পোস্ট হয়েছে।',
    payment_success_kicker: 'পেমেন্ট সম্পন্ন',
    payment_success_title: 'জার্নাল পোস্ট হয়েছে',
    payment_success_message: 'জার্নাল {voucher} পে করা হয়েছে এবং লেজারে পোস্ট হয়েছে।',
    payment_success_view_journals: 'জার্নাল দেখুন',
    payment_success_pay_another: 'আরেকটি জার্নাল পে করুন',
    back_to_list: 'জার্নাল তালিকায় ফিরে যান',
    voucher_no: 'ভাউচার নং',
    status: 'স্ট্যাটাস',
    total_debit: 'মোট ডেবিট',
    total_credit: 'মোট ক্রেডিট',
    journal_information: 'জার্নাল তথ্য',
    voucher_date: 'ভাউচার তারিখ',
    transaction_type: 'লেনদেনের ধরন',
    select_transaction_type: 'লেনদেনের ধরন খুঁজুন',
    reference_no: 'রেফারেন্স নং',
    reference_no_placeholder: 'রেফারেন্স নং লিখুন',
    party_type: 'পার্টির ধরন',
    select_party_type: 'পার্টির ধরন খুঁজুন',
    party_ledger: 'পার্টি / লেজার',
    select_party: 'কোড বা নাম দিয়ে পার্টি খুঁজুন',
    loading_parties: 'পার্টি লোড হচ্ছে...',
    project_client_demand: 'জব / ডিমান্ড লেটার',
    tab_jobs: 'জব',
    tab_demand_letters: 'ডিমান্ড লেটার',
    select_project: 'জব / ডিমান্ড লেটার খুঁজুন',
    select_demand_letter: 'ডিমান্ড লেটার খুঁজুন',
    loading_jobs: 'জব লোড হচ্ছে...',
    loading_demand_letters: 'ডিমান্ড লেটার লোড হচ্ছে...',
    no_jobs_found: 'কোনো জব পাওয়া যায়নি',
    no_demand_letters_found: 'কোনো ডিমান্ড লেটার পাওয়া যায়নি',
    journal_lines: 'জার্নাল লাইন',
    balance_hint: 'পোস্ট করার আগে ডেবিট ও ক্রেডিট সমান হতে হবে।',
    add_line: 'লাইন যোগ করুন',
    account: 'অ্যাকাউন্ট',
    select_account: 'কোড বা নাম দিয়ে অ্যাকাউন্ট খুঁজুন',
    loading_accounts: 'অ্যাকাউন্ট লোড হচ্ছে...',
    sub_ledger: 'সাব-লেজার / পার্টি',
    cost_revenue_type: 'কস্ট / রেভিনিউ টাইপ',
    select_cost_type: 'টাইপ নির্বাচন করুন',
    debit_label: 'ডেবিট',
    credit_label: 'ক্রেডিট',
    action: 'অ্যাকশন',
    optional: 'ঐচ্ছিক',
    edit: 'এডিট',
    copy: 'কপি',
    ledger: 'লেজার',
    delete: 'ডিলিট',
    total: 'মোট',
    difference: 'পার্থক্য',
    balanced: 'ব্যালান্সড',
    unbalanced: 'আনব্যালান্সড',
    narration: 'ন্যারেশন',
    narration_subtitle: 'এই জার্নাল এন্ট্রির উদ্দেশ্য বর্ণনা করুন',
    narration_hints: 'ন্যারেশন সাজেশন',
    narration_hints_suggest: 'সাজেস্ট',
    narration_hints_refresh: 'রিফ্রেশ',
    narration_hints_loading: 'তৈরি হচ্ছে...',
    narration_hints_empty: 'ন্যারেশন সাজেশন পেতে জার্নাল বিবরণ যোগ করুন।',
    narration_hints_waiting: 'আপনার জার্নাল বিবরণ থেকে সাজেশন তৈরি হচ্ছে...',
    narration_hints_pending: 'শীঘ্রই সাজেশন দেখাবে...',
    narration_hints_apply: 'এই ন্যারেশন ব্যবহার করতে ক্লিক করুন',
    narration_hints_none: 'এই এন্ট্রির জন্য কোনো সাজেশন পাওয়া যায়নি।',
    narration_hints_failed: 'ন্যারেশন সাজেশন তৈরি করা যায়নি। আবার চেষ্টা করুন।',
    narration_placeholder:
      'উদাহরণ: ফেরত আসা ক্যান্ডিডেটকে লাম্প-সাম রিক্রুটমেন্ট সার্ভিস চার্জ রিফান্ড',
    receipt: 'রসিদ',
    receipts: 'রসিদসমূহ',
    receipt_optional: 'রসিদ (ঐচ্ছিক)',
    receipt_hint: 'JPG বা PNG, প্রতিটি সর্বোচ্চ ২ MB · সর্বোচ্চ ১০টি ছবি',
    receipt_max_files: 'আপনি সর্বোচ্চ {max}টি ছবি আপলোড করতে পারেন।',
    receipt_invalid_type: 'শুধু JPG বা PNG ছবি অনুমোদিত।',
    receipt_file_too_large: 'প্রতিটি ছবি ২ MB-এর কম হতে হবে। "{name}" খুব বড়।',
    receipt_extra_skipped: 'সর্বোচ্চ {max}টি ছবি অনুমোদিত। অতিরিক্ত ফাইল বাদ দেওয়া হয়েছে।',
    receipt_preview: 'রসিদ প্রিভিউ',
    receipt_click_to_preview: 'প্রিভিউ দেখতে ক্লিক করুন',
    receipt_download: 'ডাউনলোড',
    receipt_previous: 'আগের রসিদ',
    receipt_next: 'পরের রসিদ',
    close: 'বন্ধ',
    posting_preview: 'পোস্টিং প্রিভিউ',
    posting_preview_subtitle: 'ডেবিট ও ক্রেডিট লাইনের লাইভ সারাংশ',
    posting_preview_empty: 'এখনো কোনো জার্নাল লাইন দেওয়া হয়নি',
    prepared_by: 'প্রস্তুতকারী',
    current_user: 'বর্তমান ব্যবহারকারী',
    approval: 'অনুমোদন',
    manager_required: 'ম্যানেজার প্রয়োজন',
    save_draft: 'ড্রাফট সেভ',
    submit_approval: 'অনুমোদনের জন্য সাবমিট',
    post_journal: 'জার্নাল পোস্ট',
    posting: 'পোস্ট হচ্ছে...',
    submitting: 'সাবমিট হচ্ছে...',
    posted_success: 'জার্নাল {voucher} সফলভাবে পোস্ট হয়েছে।',
    submitted_success: 'জার্নাল {voucher} অনুমোদনের জন্য সাবমিট হয়েছে।',
    error_voucher_date_required: 'ভাউচার তারিখ নির্বাচন করুন।',
    error_transaction_type_required: 'লেনদেনের ধরন নির্বাচন করুন।',
    error_min_lines: 'অ্যাকাউন্ট ও পরিমাণসহ কমপক্ষে দুটি জার্নাল লাইন দিন।',
    error_empty_row: 'সারি {row} খালি। পোস্ট করার আগে পূরণ করুন বা মুছে দিন।',
    error_empty_rows: 'সারি {rows} খালি। পোস্ট করার আগে পূরণ করুন বা মুছে দিন।',
    error_row_account_required: 'সারি {row}: একটি অ্যাকাউন্ট নির্বাচন করুন।',
    error_row_amount_required: 'সারি {row}: ডেবিট বা ক্রেডিট পরিমাণ দিন।',
    error_row_both_amounts: 'সারি {row}: একই লাইনে ডেবিট ও ক্রেডিট দুটোই দেওয়া যাবে না।',
    error_unbalanced: 'পোস্ট করার আগে ডেবিট ও ক্রেডিট সমান হতে হবে।',
    dr: 'ডেবিট',
    cr: 'ক্রেডিট',
    view: 'দেখুন',
    view_title: 'জার্নাল বিবরণ',
    loading_journal: 'জার্নাল লোড হচ্ছে...',
    error_loading_journal: 'এই জার্নাল লোড করা যায়নি।',
    created_by: 'তৈরি করেছেন',
    created_at: 'তৈরির সময়',
    reversed_by: 'রিভার্স করেছেন',
    reversed_at: 'রিভার্সের সময়',
    reverse: 'রিভার্স',
    reverse_journal: 'জার্নাল রিভার্স',
    reversing: 'রিভার্স হচ্ছে...',
    reversed: 'রিভার্সড',
    reversed_success: 'জার্নাল {voucher} সফলভাবে রিভার্স হয়েছে।',
    reverse_confirm_title: 'এই জার্নাল রিভার্স করবেন?',
    reverse_confirm_text: 'এটি {voucher}-এর জন্য একটি রিভার্সিং এন্ট্রি তৈরি করবে এবং মূল জার্নাল রিভার্সড হিসেবে চিহ্নিত করবে।',
    reversal_of: 'রিভার্স অফ',
    view_reversal_entry: 'রিভার্স এন্ট্রি {voucher} দেখুন',
  },
  journal_transaction_types: {
    module: 'লেনদেনের ধরন',
    management: 'লেনদেনের ধরন ব্যবস্থাপনা',
    add: 'লেনদেনের ধরন যোগ করুন',
    edit: 'লেনদেনের ধরন সম্পাদনা',
    view: 'লেনদেনের ধরন দেখুন',
    information: 'লেনদেনের ধরন তথ্য',
    code: 'কোড',
    name: 'নাম',
    sort_order: 'ক্রম',
  },
}
