export default {
  journals: {
    module: 'Journal',
    management: 'Journal Management',
    sheet_title: 'Journal Entries',
    je_no: 'JE No.',
    date: 'Date',
    transaction: 'Transaction / Test Case',
    account_code: 'Account Code',
    account_name: 'Account Name',
    party_ref: 'Party / Ref',
    debit: 'Debit (BDT)',
    credit: 'Credit (BDT)',
    cost_class: 'Cost Class',
    project_client: 'Jobs / Demand Letters',
    static_note: 'Showing posted journals from the system',
    empty_note: 'No journals found yet. Post a journal to see it here.',
    loading: 'Loading journals...',

    post_title: 'Post Journal',
    post_static_note: 'Enter journal information and lines, then post to the ledger.',
    tab_bill_entry: 'Bill Entry',
    tab_approval: 'Approval',
    tab_payment: 'Payment',
    approval_tab_placeholder: 'Approval workflow content will appear here.',
    payment_tab_placeholder: 'Payment content will appear here.',
    approval_select_title: 'Journals Waiting for Approval',
    approval_select_hint: 'Select a submitted journal to review a read-only preview.',
    select_pending_journal: 'Pending Journal',
    search_pending_journal: 'Search by voucher, party, or reference',
    loading_pending_journals: 'Loading pending journals...',
    no_pending_journals: 'No journals waiting for approval',
    no_pending_journals_hint: 'Submit a journal for approval from the Bill Entry tab.',
    select_journal_to_preview: 'Select a journal to preview',
    select_journal_to_preview_hint: 'Use the search above to choose a waiting journal.',
    waiting_for_approval: 'Waiting for Approval',
    approved: 'Approved',
    balance: 'Balance',
    lines_count: 'lines',
    submitted_at: 'Submitted At',
    manager_comment: 'Manager Comment',
    manager_comment_placeholder: 'Add approval remarks for payment team...',
    approve_journal: 'Approve',
    approving: 'Approving...',
    clear_selection: 'Clear Selection',
    approved_success: 'Journal {voucher} approved successfully.',
    error_manager_comment_required: 'Please enter a manager comment before approving.',
    error_return_comment_required: 'Please enter a return comment before sending back.',
    manager_action_hint: 'Add remarks to approve or return the journal to the accountant.',
    manager_action_placeholder: 'Explain what to fix, or add approval notes for payment...',
    return_journal: 'Return',
    returning: 'Returning...',
    returned: 'Returned',
    returned_success: 'Journal {voucher} returned to Bill Entry.',
    returned_select_title: 'Returned Journals',
    returned_select_hint: 'Select a returned journal to update and resubmit for approval.',
    select_returned_journal: 'Returned Journal',
    search_returned_journal: 'Search by voucher, party, or reference',
    loading_returned_journals: 'Loading returned journals...',
    no_returned_journals: 'No returned journals',
    manager_return_comment: 'Manager Return Comment',
    manager_return_comment_hint: 'Update the journal according to this comment, then resubmit for approval.',
    resubmit_approval: 'Re Submit For Approval',
    resubmitting: 'Resubmitting...',
    resubmitted_success: 'Journal {voucher} resubmitted for approval.',
    success_kicker_submitted: 'Bill Entry Complete',
    success_kicker_resubmitted: 'Resubmitted',
    success_kicker_posted: 'Posted',
    success_title_submitted: 'Submitted for Approval',
    success_title_resubmitted: 'Resubmitted for Approval',
    success_title_posted: 'Journal Posted Successfully',
    success_message_submitted: 'Journal {voucher} has been saved and sent to the manager for approval.',
    success_message_resubmitted: 'Journal {voucher} has been updated and sent back for approval.',
    success_message_posted: 'Journal {voucher} has been posted to the ledger.',
    success_go_to_approval: 'Go to Approval',
    success_view_journals: 'View Journals',
    success_create_new: 'Create New Entry',
    approval_success_kicker: 'Approval Complete',
    approval_success_title: 'Journal Approved',
    approval_success_message: 'Journal {voucher} has been approved and is ready for payment.',
    approval_success_go_to_payment: 'Go to Payment',
    approval_success_review_more: 'Review More Approvals',
    payment_select_title: 'Approved Journals Ready for Payment',
    payment_select_hint: 'Select an approved journal, edit if needed, then pay to post.',
    select_approved_journal: 'Approved Journal',
    search_approved_journal: 'Search by voucher, party, or reference',
    loading_approved_journals: 'Loading approved journals...',
    no_approved_journals: 'No approved journals ready for payment',
    no_approved_journals_hint: 'Approve a journal from the Approval tab first.',
    select_journal_to_pay: 'Select a journal to pay',
    select_journal_to_pay_hint: 'Use the search above to choose an approved journal.',
    pay_journal: 'Pay',
    paying: 'Paying...',
    paid_success: 'Journal {voucher} paid and posted successfully.',
    payment_success_kicker: 'Payment Complete',
    payment_success_title: 'Journal Posted',
    payment_success_message: 'Journal {voucher} has been paid and posted to the ledger.',
    payment_success_view_journals: 'View Journals',
    payment_success_pay_another: 'Pay Another Journal',
    back_to_list: 'Back to Journals',
    voucher_no: 'Voucher No.',
    status: 'Status',
    total_debit: 'Total Debit',
    total_credit: 'Total Credit',
    journal_information: 'Journal Information',
    voucher_date: 'Voucher Date',
    transaction_type: 'Transaction Type',
    select_transaction_type: 'Search transaction type',
    reference_no: 'Reference No.',
    reference_no_placeholder: 'Enter reference no.',
    party_type: 'Party Type',
    select_party_type: 'Search party type',
    party_ledger: 'Party / Ledger',
    select_party: 'Search party by code or name',
    loading_parties: 'Loading parties...',
    project_client_demand: 'Jobs / Demand Letters',
    tab_jobs: 'Jobs',
    tab_demand_letters: 'Demand Letters',
    select_project: 'Search job / demand letter',
    select_demand_letter: 'Search demand letter',
    loading_jobs: 'Loading jobs...',
    loading_demand_letters: 'Loading demand letters...',
    no_jobs_found: 'No jobs found',
    no_demand_letters_found: 'No demand letters found',
    journal_lines: 'Journal Lines',
    balance_hint: 'Debit must equal Credit before posting.',
    add_line: 'Add Line',
    account: 'Account',
    select_account: 'Search account by code or name',
    loading_accounts: 'Loading accounts...',
    sub_ledger: 'Sub-ledger / Party',
    cost_revenue_type: 'Cost / Revenue Type',
    select_cost_type: 'Select type',
    debit_label: 'Debit',
    credit_label: 'Credit',
    action: 'Action',
    optional: 'Optional',
    edit: 'Edit',
    copy: 'Copy',
    ledger: 'Ledger',
    delete: 'Delete',
    total: 'Total',
    difference: 'Difference',
    balanced: 'Balanced',
    unbalanced: 'Unbalanced',
    narration: 'Narration',
    narration_subtitle: 'Describe the purpose of this journal entry',
    narration_placeholder:
      'Example: Lump-sum recruitment service charge refund to returned candidate',
    receipt: 'Receipt',
    receipts: 'Receipts',
    receipt_optional: 'Receipt (Optional)',
    receipt_hint: 'JPG or PNG, max 2 MB each · up to 10 images',
    receipt_max_files: 'You can upload up to {max} images.',
    receipt_invalid_type: 'Only JPG or PNG images are allowed.',
    receipt_file_too_large: 'Each image must be under 2 MB. "{name}" is too large.',
    receipt_extra_skipped: 'Only {max} images allowed. Extra files were skipped.',
    receipt_preview: 'Receipt Preview',
    receipt_click_to_preview: 'Click to preview',
    receipt_download: 'Download',
    receipt_previous: 'Previous receipt',
    receipt_next: 'Next receipt',
    close: 'Close',
    posting_preview: 'Posting Preview',
    posting_preview_subtitle: 'Live summary of debit and credit lines',
    posting_preview_empty: 'No journal lines entered yet',
    prepared_by: 'Prepared by',
    current_user: 'Current User',
    approval: 'Approval',
    manager_required: 'Manager Required',
    save_draft: 'Save Draft',
    submit_approval: 'Submit for Approval',
    post_journal: 'Post Journal',
    posting: 'Posting...',
    submitting: 'Submitting...',
    posted_success: 'Journal {voucher} posted successfully.',
    submitted_success: 'Journal {voucher} submitted for approval.',
    error_voucher_date_required: 'Please select a voucher date.',
    error_transaction_type_required: 'Please select a transaction type.',
    error_min_lines: 'Add at least two journal lines with accounts and amounts.',
    error_empty_row: 'Row {row} is empty. Please fill it in or delete the row before posting.',
    error_empty_rows: 'Rows {rows} are empty. Please fill them in or delete those rows before posting.',
    error_row_account_required: 'Row {row}: please select an account.',
    error_row_amount_required: 'Row {row}: enter a debit or credit amount.',
    error_row_both_amounts: 'Row {row}: a line cannot have both debit and credit.',
    error_unbalanced: 'Debit and credit totals must be equal before posting.',
    dr: 'Dr',
    cr: 'Cr',
    view: 'View',
    view_title: 'Journal Details',
    loading_journal: 'Loading journal...',
    error_loading_journal: 'Unable to load this journal.',
    created_by: 'Created By',
    created_at: 'Created At',
    reversed_by: 'Reversed By',
    reversed_at: 'Reversed At',
    reverse: 'Reverse',
    reverse_journal: 'Reverse Journal',
    reversing: 'Reversing...',
    reversed: 'Reversed',
    reversed_success: 'Journal {voucher} has been reversed successfully.',
    reverse_confirm_title: 'Reverse this journal?',
    reverse_confirm_text: 'This will create a reversing entry for {voucher} and mark the original as reversed.',
    reversal_of: 'Reversal of',
    view_reversal_entry: 'View reversal entry {voucher}',
  },
  journal_transaction_types: {
    module: 'Transaction Type',
    management: 'Transaction Type Management',
    add: 'Add Transaction Type',
    edit: 'Edit Transaction Type',
    view: 'View Transaction Type',
    information: 'Transaction Type Information',
    code: 'Code',
    name: 'Name',
    sort_order: 'Sort Order',
  },
}
