export default {
  parties: {
    module: 'পার্টি',
    management: 'পার্টি ব্যবস্থাপনা',
    add: 'পার্টি যোগ করুন',
    edit: 'পার্টি সম্পাদনা',
    view: 'পার্টি দেখুন',
    information: 'পার্টি তথ্য',
    party_id: 'পার্টি আইডি',
    party_type: 'পার্টির ধরন',
    name: 'নাম',
    opening_debit: 'ওপেনিং ডেবিট',
    opening_credit: 'ওপেনিং ক্রেডিট',
    remarks: 'মন্তব্য',
    all_types: 'সব ধরন',
    all_statuses: 'সব স্ট্যাটাস',
    select_client: 'ক্লায়েন্ট নির্বাচন করুন',
    select_principal: 'প্রিন্সিপাল নির্বাচন করুন',
    select_agent: 'এজেন্ট নির্বাচন করুন',
    select_candidate: 'ক্যান্ডিডেট নির্বাচন করুন',
    select_vendor: 'ভেন্ডর নির্বাচন করুন',
    select_staff: 'স্টাফ নির্বাচন করুন',
    loading_source: 'তালিকা লোড হচ্ছে...',
    search_source: 'কোড বা নাম দিয়ে খুঁজুন',
    no_source_options: 'কোনো উপলব্ধ রেকর্ড নেই (সব ইতিমধ্যে পার্টি হিসেবে যোগ করা হয়েছে)',
    select_job: 'জব নির্বাচন করুন',
    search_job: 'জবের নাম বা কোড দিয়ে খুঁজুন',
    select_job_to_load_candidates: 'ক্যান্ডিডেট লোড করতে একটি জব নির্বাচন করুন',
    add_multiple: 'একাধিক পার্টি যোগ করুন',
    bulk_add_title: 'একাধিক পার্টি যোগ করুন',
    bulk_add_hint: 'পার্টির ধরন নির্বাচন করুন, তারপর এক বা একাধিক সারি যোগ করুন। সোর্স নির্বাচন করলে পার্টি আইডি ও নাম অটো-ফিল হবে।',
    add_row: 'সারি যোগ করুন',
    save_all: 'সব পার্টি সংরক্ষণ করুন',
    bulk_ready: '{count}টি পার্টি সফলভাবে সংরক্ষণ হয়েছে।',
    bulk_validation_failed: 'সংরক্ষণের আগে সমস্যাগুলো ঠিক করুন।',
    bulk_error_party_type_required: 'আগে পার্টির ধরন নির্বাচন করুন।',
    bulk_error_min_one_row: 'কমপক্ষে একটি পার্টি সারি যোগ করুন।',
    bulk_error_all_rows_empty: 'সংরক্ষণের আগে কমপক্ষে একটি পার্টি সারি পূরণ করুন।',
    bulk_error_empty_row:
      'সারি {row} খালি আছে। সংরক্ষণের আগে পূরণ করুন অথবা সারিটি মুছে ফেলুন।',
    bulk_error_empty_rows:
      'সারি {rows} খালি আছে। সংরক্ষণের আগে পূরণ করুন অথবা সেই সারিগুলো মুছে ফেলুন।',
    bulk_error_row_select_source: 'সারি {row}: একটি {type} নির্বাচন করুন।',
    bulk_error_row_empty_required: 'সারি {row}: পার্টি আইডি এবং নাম আবশ্যক।',
    bulk_error_row_party_id_required: 'সারি {row}: পার্টি আইডি আবশ্যক।',
    bulk_error_row_name_required: 'সারি {row}: নাম আবশ্যক।',
    bulk_error_row_duplicate_party_id: 'সারি {row}: এই ব্যাচে পার্টি আইডি "{code}" ডুপ্লিকেট।',
    action: 'অ্যাকশন',
    copy: 'কপি',
    delete: 'ডিলিট',
    total_rows: 'মোট সারি',
  },
  party_types: {
    module: 'পার্টি টাইপ',
    management: 'পার্টি টাইপ ব্যবস্থাপনা',
    add: 'পার্টি টাইপ যোগ করুন',
    edit: 'পার্টি টাইপ সম্পাদনা',
    view: 'পার্টি টাইপ দেখুন',
    information: 'পার্টি টাইপ তথ্য',
    code: 'কোড',
    name: 'নাম',
    sort_order: 'ক্রম',
    apply_job_filter: 'জব ফিল্টার প্রয়োগ করুন',
  },
}
