export default {
  parties: {
    module: 'পার্টি',
    management: 'পার্টি ব্যবস্থাপনা',
    add: 'পার্টি যোগ করুন',
    edit: 'পার্টি সম্পাদনা',
    view: 'পার্টি দেখুন',
    information: 'পার্টি তথ্য',
    party_id: 'পার্টি আইডি',
    party_type: 'পার্টির ধরন',
    name: 'নাম',
    opening_debit: 'ওপেনিং ডেবিট',
    opening_credit: 'ওপেনিং ক্রেডিট',
    remarks: 'মন্তব্য',
    all_types: 'সব ধরন',
    all_statuses: 'সব স্ট্যাটাস',
    select_client: 'ক্লায়েন্ট নির্বাচন করুন',
    select_principal: 'প্রিন্সিপাল নির্বাচন করুন',
    select_agent: 'এজেন্ট নির্বাচন করুন',
    select_candidate: 'ক্যান্ডিডেট নির্বাচন করুন',
    select_vendor: 'ভেন্ডর নির্বাচন করুন',
    select_staff: 'স্টাফ নির্বাচন করুন',
    loading_source: 'তালিকা লোড হচ্ছে...',
    search_source: 'কোড বা নাম দিয়ে খুঁজুন',
    select_job: 'জব নির্বাচন করুন',
    search_job: 'জবের নাম বা কোড দিয়ে খুঁজুন',
    select_job_to_load_candidates: 'ক্যান্ডিডেট লোড করতে একটি জব নির্বাচন করুন',
    add_multiple: 'একাধিক পার্টি যোগ করুন',
    bulk_add_title: 'একাধিক পার্টি যোগ করুন',
    bulk_add_hint: 'পার্টির ধরন নির্বাচন করুন, তারপর এক বা একাধিক সারি যোগ করুন। সোর্স নির্বাচন করলে পার্টি আইডি ও নাম অটো-ফিল হবে।',
    add_row: 'সারি যোগ করুন',
    save_all: 'সব পার্টি সংরক্ষণ করুন',
    bulk_ready: '{count}টি পার্টি সফলভাবে সংরক্ষণ হয়েছে।',
    bulk_validation_failed: 'সংরক্ষণের আগে সমস্যাগুলো ঠিক করুন।',
    action: 'অ্যাকশন',
    copy: 'কপি',
    delete: 'ডিলিট',
    total_rows: 'মোট সারি',
  },
}
