export default {
  parties: {
    module: 'Party',
    management: 'Party Management',
    add: 'Add Party',
    edit: 'Edit Party',
    view: 'View Party',
    information: 'Party Information',
    party_id: 'Party ID',
    party_type: 'Party Type',
    name: 'Name',
    opening_debit: 'Opening Debit',
    opening_credit: 'Opening Credit',
    remarks: 'Remarks',
    all_types: 'All Types',
    all_statuses: 'All Statuses',
    select_client: 'Select Client',
    select_principal: 'Select Principal',
    select_agent: 'Select Agent',
    select_candidate: 'Select Candidate',
    select_vendor: 'Select Vendor',
    select_staff: 'Select Staff',
    loading_source: 'Loading list...',
    search_source: 'Search by code or name',
    no_source_options: 'No available records (all already added as parties)',
    select_job: 'Select Job',
    search_job: 'Search by job name or code',
    select_job_to_load_candidates: 'Select a job to load candidates',
    add_multiple: 'Add Multiple Parties',
    bulk_add_title: 'Add Multiple Parties',
    bulk_add_hint: 'Select a party type, then add one or more rows. Source selection auto-fills party ID and name.',
    add_row: 'Add Row',
    save_all: 'Save All Parties',
    bulk_ready: '{count} parties saved successfully.',
    bulk_validation_failed: 'Please fix the highlighted issues before saving.',
    bulk_error_party_type_required: 'Please select a party type first.',
    bulk_error_min_one_row: 'Add at least one party row.',
    bulk_error_all_rows_empty: 'Please fill at least one party row before saving.',
    bulk_error_empty_row:
      'Row {row} is empty. Please fill it in or delete the row before saving.',
    bulk_error_empty_rows:
      'Rows {rows} are empty. Please fill them in or delete those rows before saving.',
    bulk_error_row_select_source: 'Row {row}: please select a {type}.',
    bulk_error_row_empty_required: 'Row {row}: Party ID and Name are required.',
    bulk_error_row_party_id_required: 'Row {row}: Party ID is required.',
    bulk_error_row_name_required: 'Row {row}: Name is required.',
    bulk_error_row_duplicate_party_id: 'Row {row}: duplicate Party ID "{code}" in this batch.',
    action: 'Action',
    copy: 'Copy',
    delete: 'Delete',
    total_rows: 'Total Rows',
  },
  party_types: {
    module: 'Party Type',
    management: 'Party Type Management',
    add: 'Add Party Type',
    edit: 'Edit Party Type',
    view: 'View Party Type',
    information: 'Party Type Information',
    code: 'Code',
    name: 'Name',
    sort_order: 'Sort Order',
    apply_job_filter: 'Apply Job Filter',
  },
}
