export default {
  parties: {
    module: 'Party',
    management: 'Party Management',
    add: 'Add Party',
    edit: 'Edit Party',
    view: 'View Party',
    information: 'Party Information',
    party_id: 'Party ID',
    party_type: 'Party Type',
    name: 'Name',
    opening_debit: 'Opening Debit',
    opening_credit: 'Opening Credit',
    remarks: 'Remarks',
    all_types: 'All Types',
    all_statuses: 'All Statuses',
    select_client: 'Select Client',
    select_principal: 'Select Principal',
    select_agent: 'Select Agent',
    select_candidate: 'Select Candidate',
    select_vendor: 'Select Vendor',
    select_staff: 'Select Staff',
    loading_source: 'Loading list...',
    search_source: 'Search by code or name',
    select_job: 'Select Job',
    search_job: 'Search by job name or code',
    select_job_to_load_candidates: 'Select a job to load candidates',
    add_multiple: 'Add Multiple Parties',
    bulk_add_title: 'Add Multiple Parties',
    bulk_add_hint: 'Select a party type, then add one or more rows. Source selection auto-fills party ID and name.',
    add_row: 'Add Row',
    save_all: 'Save All Parties',
    bulk_ready: '{count} parties saved successfully.',
    bulk_validation_failed: 'Please fix the highlighted issues before saving.',
    action: 'Action',
    copy: 'Copy',
    delete: 'Delete',
    total_rows: 'Total Rows',
  },
}
