export default {
  parties: {
    module: 'Party',
    management: 'Party Management',
    add: 'Add Party',
    edit: 'Edit Party',
    view: 'View Party',
    information: 'Party Information',
    party_id: 'Party ID',
    party_type: 'Party Type',
    name: 'Name',
    opening_debit: 'Opening Debit',
    opening_credit: 'Opening Credit',
    remarks: 'Remarks',
    all_types: 'All Types',
    all_statuses: 'All Statuses',
    select_client: 'Select Client',
    select_principal: 'Select Principal',
    select_agent: 'Select Agent',
    select_candidate: 'Select Candidate',
    select_vendor: 'Select Vendor',
    select_staff: 'Select Staff',
    loading_source: 'Loading list...',
    search_source: 'Search by code or name',
  },
}
