export default {
  accounts: {
    module: 'Chart of Accounts',
    management: 'Chart of Accounts ব্যবস্থাপনা',
    add: 'অ্যাকাউন্ট যোগ করুন',
    edit: 'অ্যাকাউন্ট সম্পাদনা',
    view: 'অ্যাকাউন্ট দেখুন',
    information: 'অ্যাকাউন্ট তথ্য',
    code: 'কোড',
    account_name: 'অ্যাকাউন্টের নাম',
    type: 'ধরন',
    financial_statement: 'আর্থিক বিবরণী',
    normal_balance: 'স্বাভাবিক ব্যালেন্স',
    description: 'বিবরণ',
    all_types: 'সব ধরন',
    all_statements: 'সব বিবরণী',
    all_balances: 'সব ব্যালেন্স',
    all_statuses: 'সব স্ট্যাটাস',
    trial_balance: 'ট্রায়াল ব্যালেন্স',
    trial_balance_note: 'পোস্ট করা জার্নাল থেকে অ্যাকাউন্ট ব্যালেন্স, প্রতিটি অ্যাকাউন্টের স্বাভাবিক ব্যালেন্স অনুযায়ী।',
    from_date: 'শুরুর তারিখ',
    to_date: 'শেষ তারিখ',
    refresh: 'রিফ্রেশ',
    loading_trial_balance: 'ট্রায়াল ব্যালেন্স লোড হচ্ছে...',
    trial_balance_empty: 'এই সময়ের জন্য কোনো অ্যাকাউন্ট ব্যালেন্স পাওয়া যায়নি।',
    trial_balance_load_error: 'ট্রায়াল ব্যালেন্স লোড করা যায়নি।',
    debit: 'ডেবিট',
    credit: 'ক্রেডিট',
    total: 'মোট',
    balanced: 'ব্যালান্সড!',
    not_balanced: 'ব্যালান্স নয় — পার্থক্য {amount}',
    debit_heavier: 'ডেবিট বেশি',
    credit_heavier: 'ক্রেডিট বেশি',
    period_range: '{from} থেকে {to}',
    period_as_of: '{date} পর্যন্ত',
    gross_profit: 'মোট লাভ',
    gross_profit_note: 'পোস্ট করা জার্নাল থেকে revenue বিয়োগ direct cost (শুধু Gross Profit অ্যাকাউন্ট)।',
    loading_gross_profit: 'মোট লাভ লোড হচ্ছে...',
    gross_profit_empty: 'এই সময়ের জন্য কোনো মোট লাভ তথ্য পাওয়া যায়নি।',
    gross_profit_load_error: 'মোট লাভ লোড করা যায়নি।',
    amount: 'পরিমাণ',
    total_revenue: 'মোট revenue',
    total_contra_revenue: 'Contra revenue',
    total_direct_cost: 'মোট direct cost',
  },
}
