export default {
  accounts: {
    module: 'চার্ট অব অ্যাকাউন্টস',
    management: 'চার্ট অব অ্যাকাউন্টস ব্যবস্থাপনা',
    add: 'অ্যাকাউন্ট যোগ করুন',
    edit: 'অ্যাকাউন্ট সম্পাদনা',
    view: 'অ্যাকাউন্ট দেখুন',
    information: 'অ্যাকাউন্ট তথ্য',
    code: 'কোড',
    account_name: 'অ্যাকাউন্টের নাম',
    type: 'ধরন',
    financial_statement: 'আর্থিক বিবরণী',
    normal_balance: 'স্বাভাবিক ব্যালেন্স',
    description: 'বিবরণ',
    all_types: 'সব ধরন',
    all_statements: 'সব বিবরণী',
    all_balances: 'সব ব্যালেন্স',
    all_statuses: 'সব স্ট্যাটাস',
    trial_balance: 'ট্রায়াল ব্যালেন্স',
    trial_balance_note: 'পোস্ট করা জার্নাল থেকে অ্যাকাউন্ট ব্যালেন্স, প্রতিটি অ্যাকাউন্টের স্বাভাবিক ব্যালেন্স অনুযায়ী।',
    from_date: 'শুরুর তারিখ',
    to_date: 'শেষ তারিখ',
    refresh: 'রিফ্রেশ',
    filter: 'ফিল্টার',
    loading_trial_balance: 'ট্রায়াল ব্যালেন্স লোড হচ্ছে...',
    trial_balance_empty: 'এই সময়ের জন্য কোনো অ্যাকাউন্ট ব্যালেন্স পাওয়া যায়নি।',
    trial_balance_load_error: 'ট্রায়াল ব্যালেন্স লোড করা যায়নি।',
    debit: 'ডেবিট',
    credit: 'ক্রেডিট',
    total: 'মোট',
    balanced: 'ব্যালান্সড!',
    not_balanced: 'ব্যালান্স নয় — পার্থক্য {amount}',
    debit_heavier: 'ডেবিট বেশি',
    credit_heavier: 'ক্রেডিট বেশি',
    period_range: '{from} থেকে {to}',
    period_as_of: '{date} পর্যন্ত',
    gross_profit: 'মোট লাভ',
    gross_profit_note: 'পোস্ট করা জার্নালের সাব-লেজার (পাসপোর্ট নম্বর) থেকে প্রার্থীভিত্তিক মোট লাভ (শুধু মোট লাভ অ্যাকাউন্ট)।',
    loading_gross_profit: 'মোট লাভ লোড হচ্ছে...',
    gross_profit_empty: 'এই সময়ের জন্য কোনো মোট লাভ তথ্য পাওয়া যায়নি।',
    gross_profit_load_error: 'মোট লাভ লোড করা যায়নি।',
    gross_profit_candidates: 'প্রার্থীভিত্তিক মোট লাভ',
    gross_profit_candidates_note: 'নির্বাচিত ফিল্টার অনুযায়ী sub-ledger পাসপোর্ট নম্বরের বিস্তারিত।',
    gross_profit_breakdown: 'বিস্তারিত রিপোর্ট',
    gross_profit_breakdown_preview: 'ব্যাকএন্ড PDF প্রিভিউ',
    gross_profit_breakdown_footer: 'বর্তমান ফিল্টার ও sub-ledger পাসপোর্ট থেকে প্রার্থীভিত্তিক বিস্তারিত।',
    view_breakdown_report: 'বিস্তারিত রিপোর্ট দেখুন',
    download_breakdown_report: 'বিস্তারিত রিপোর্ট ডাউনলোড',
    opening_breakdown: 'খোলা হচ্ছে...',
    generating_pdf: 'PDF তৈরি হচ্ছে...',
    generating_preview: 'প্রিভিউ তৈরি হচ্ছে',
    breakdown_pdf_generated: 'বিস্তারিত PDF ডাউনলোড হয়েছে।',
    breakdown_pdf_load_error: 'বিস্তারিত PDF লোড করা যায়নি।',
    download: 'ডাউনলোড',
    print: 'প্রিন্ট',
    preparing_print: 'প্রিন্ট প্রস্তুত হচ্ছে...',
    close: 'বন্ধ',
    progress: 'অগ্রগতি',
    please_wait_preview: 'অনুগ্রহ করে অপেক্ষা করুন। এই পৃষ্ঠা বন্ধ করবেন না।',
    download_ready: 'ডাউনলোড প্রস্তুত',
    preparing_file: 'ফাইল প্রস্তুত করা হচ্ছে…',
    building_report: 'সার্ভার থেকে রিপোর্ট তৈরি হচ্ছে…',
    collecting_report_data: 'রিপোর্ট ডেটা সংগ্রহ হচ্ছে…',
    opening_pdf_preview: 'PDF প্রিভিউ খোলা হচ্ছে…',
    preparing_preview: 'প্রিভিউ প্রস্তুত করা হচ্ছে…',
    preview_load_failed: 'PDF প্রিভিউ লোড করা যায়নি',
    try_again: 'আবার চেষ্টা করুন',
    press_esc_to_close: 'বন্ধ করতে Esc চাপুন',
    allow_popups_to_print: 'রিপোর্ট প্রিন্ট করতে পপ-আপ অনুমতি দিন।',
    filter_job: 'জব',
    filter_demand_letter: 'ডিমান্ড লেটার',
    filter_client: 'ক্লায়েন্ট',
    filter_agent: 'এজেন্ট',
    filter_principal: 'প্রিন্সিপাল',
    reset_filters: 'ফিল্টার রিসেট',
    search: 'খুঁজুন',
    passport_no: 'পাসপোর্ট নম্বর',
    candidate_name: 'প্রার্থী',
    amount: 'পরিমাণ',
    total_revenue: 'মোট রেভিনিউ',
    total_contra_revenue: 'কন্ট্রা রেভিনিউ',
    total_direct_cost: 'মোট প্রত্যক্ষ খরচ',
    income_statement: 'আয় বিবরণী',
    income_statement_note: 'নিয়ে আসা মোট লাভসহ পোস্ট করা জার্নালের আয় বিবরণী অ্যাকাউন্ট থেকে।',
    loading_income_statement: 'আয় বিবরণী লোড হচ্ছে...',
    income_statement_empty: 'এই সময়ের জন্য কোনো আয় বিবরণী তথ্য পাওয়া যায়নি।',
    income_statement_load_error: 'আয় বিবরণী লোড করা যায়নি।',
    gross_profit_brought_down: 'মোট লাভ স্থানান্তর (b/d)',
    total_other_income: 'অন্যান্য আয়',
    total_expenses: 'মোট ব্যয়',
    net_profit: 'নিট লাভ',
    net_loss: 'নিট ক্ষতি',
    account_type_asset: 'সম্পদ',
    account_type_contra_asset: 'কন্ট্রা সম্পদ',
    account_type_liability: 'দায়',
    account_type_equity: 'ইকুইটি',
    account_type_contra_equity: 'কন্ট্রা ইকুইটি',
    account_type_revenue: 'রেভিনিউ',
    account_type_contra_revenue: 'কন্ট্রা রেভিনিউ',
    account_type_other_operating_revenue: 'অন্যান্য পরিচালন রেভিনিউ',
    account_type_other_income: 'অন্যান্য আয়',
    account_type_direct_cost_a: 'প্রত্যক্ষ খরচ ক',
    account_type_direct_cost_b: 'প্রত্যক্ষ খরচ খ',
    account_type_operating_expense: 'পরিচালন ব্যয়',
    account_type_finance_cost: 'অর্থায়ন ব্যয়',
    account_type_other_expense: 'অন্যান্য ব্যয়',
    balance_sheet: 'ব্যালেন্স শিট',
    balance_sheet_note: 'নির্বাচিত তারিখ পর্যন্ত পোস্ট করা জার্নাল থেকে সম্পদ, দায় ও ইকুইটি।',
    as_of_date: 'যে তারিখ পর্যন্ত',
    loading_balance_sheet: 'ব্যালেন্স শিট লোড হচ্ছে...',
    balance_sheet_empty: 'এই তারিখের জন্য কোনো ব্যালেন্স শিট ব্যালেন্স পাওয়া যায়নি।',
    balance_sheet_load_error: 'ব্যালেন্স শিট লোড করা যায়নি।',
    assets: 'সম্পদ',
    liabilities: 'দায়',
    equity: 'ইকুইটি',
    total_assets: 'মোট সম্পদ',
    total_liabilities: 'মোট দায়',
    total_equity: 'মোট ইকুইটি',
    total_liabilities_and_equity: 'মোট দায় ও ইকুইটি',
    current_year_profit: 'চলতি বছরের লাভ',
    current_year_loss: 'চলতি বছরের ক্ষতি',
    balance_sheet_period: '{from} থেকে {to} পর্যন্ত লাভ · {to} পর্যন্ত ব্যালেন্স',
    balance_sheet_balanced: 'ব্যালেন্স শিট ব্যালান্সড (সম্পদ = দায় + ইকুইটি)।',
    balance_sheet_not_balanced: 'ব্যালান্সড নয় — পার্থক্য {amount}',
  },
}
