export default {
  accounts: {
    module: 'Chart of Accounts',
    management: 'Chart of Accounts Management',
    add: 'Add Account',
    edit: 'Edit Account',
    view: 'View Account',
    information: 'Account Information',
    code: 'Code',
    account_name: 'Account Name',
    type: 'Type',
    financial_statement: 'Financial Statement',
    normal_balance: 'Normal Balance',
    description: 'Description',
    all_types: 'All Types',
    all_statements: 'All Statements',
    all_balances: 'All Balances',
    all_statuses: 'All Statuses',
    trial_balance: 'Trial Balance',
    trial_balance_note: 'Account balances from posted journals, using each account\'s normal balance.',
    from_date: 'From Date',
    to_date: 'To Date',
    refresh: 'Refresh',
    loading_trial_balance: 'Loading trial balance...',
    trial_balance_empty: 'No account balances found for this period.',
    trial_balance_load_error: 'Failed to load trial balance.',
    debit: 'Debit',
    credit: 'Credit',
    total: 'Total',
    balanced: 'Balanced!',
    not_balanced: 'Not balanced — difference {amount}',
    debit_heavier: 'Debit heavier',
    credit_heavier: 'Credit heavier',
    period_range: 'From {from} to {to}',
    period_as_of: 'As of {date}',
  },
}
