export default {
  employees: {
    module: 'কর্মচারী',
    management: 'কর্মচারী ম্যানেজমেন্ট',
    performance: 'কর্মচারী পারফরম্যান্স',
    add: 'কর্মচারী যোগ করুন',
    edit: 'কর্মচারী সম্পাদনা',
    view: 'কর্মচারীর বিস্তারিত',
    create: 'কর্মচারী তৈরি করুন',

    personal_info: 'ব্যক্তিগত তথ্য',
    access_status: 'অ্যাক্সেস ও স্ট্যাটাস',
    credentials: 'ক্রেডেনশিয়ালস',

    username: 'ইউজারনেম',
    department: 'বিভাগ',
    assign_roles: 'রোল নির্ধারণ',
    show_ats_summary: 'এটিএস সারসংক্ষেপ দেখান',
    manager_approval: 'ম্যানেজার অনুমোদন',
    send_credentials: 'ক্রেডেনশিয়ালস পাঠান',
    upload_document: 'ডকুমেন্ট আপলোড (ঐচ্ছিক)',
    generate_password: 'পাসওয়ার্ড তৈরি করুন',
    auto_generate_password: 'অটো-জেনারেট পাসওয়ার্ড',
    select: 'নির্বাচন করুন',

    table_view: 'টেবিল ভিউ',
    grid_view: 'গ্রিড ভিউ',
    empty: 'কোনো কর্মচারী পাওয়া যায়নি',
    empty_hint: 'ফিল্টার পরিবর্তন করুন অথবা নতুন কর্মচারী যোগ করুন।',
    tasks_count: '{count}টি টাস্ক',
    pending_count: '{count}টি অপেক্ষমাণ',

    credentials_copied: 'ক্রেডেনশিয়ালস কপি হয়েছে!',
    credentials_copy_failed: 'ক্রেডেনশিয়ালস কপি করা যায়নি। অনুগ্রহ করে ম্যানুয়ালি চেষ্টা করুন।',
    credentials_for: '{name} এর ক্রেডেনশিয়ালস:',
    login_url: 'লগইন URL',

    not_provided: 'প্রদান করা হয়নি',
    na: 'প্রযোজ্য নয়',
    employee_id_label: 'কর্মচারী আইডি',
    employee_name: 'কর্মচারীর নাম',
    points: 'পয়েন্ট',

    placeholder_name: 'যেমন: আব্দুল আলিম',
    placeholder_username: 'যেমন: johndoe',
    placeholder_email: "যেমন: rabit{'@'}example.com",
    placeholder_phone: 'যেমন: +1234567890',
  },

  departments: {
    module: 'বিভাগ',
    management: 'বিভাগ ম্যানেজমেন্ট',
    add: 'বিভাগ যোগ করুন',
    edit: 'বিভাগ সম্পাদনা',
    view: 'বিভাগের বিস্তারিত',
    create: 'বিভাগ তৈরি করুন',
    name: 'নাম',
    placeholder_name: 'বিভাগের নাম লিখুন',
    department_id: 'বিভাগ আইডি',
    employees_assigned: '{count} জন কর্মচারী নিয়োজিত | {count} জন কর্মচারী নিয়োজিত',
    employees: 'কর্মচারী',
  },

  designations: {
    module: 'পদবী',
    management: 'পদবী ম্যানেজমেন্ট',
    add: 'পদবী যোগ করুন',
    edit: 'পদবী সম্পাদনা',
    view: 'পদবীর বিস্তারিত',
    delete: 'পদবী মুছুন',
    delete_confirm: 'আপনি কি নিশ্চিত যে এই পদবীটি মুছে ফেলতে চান?',
    bulk_delete_confirm: 'নির্বাচিত রেকর্ডগুলো মুছে ফেলতে চান?',
    info: 'পদবীর তথ্য',
    name: 'নাম',
    description: 'বিবরণ',
    placeholder_name: 'যেমন: ম্যানেজার',
    placeholder_description: 'পদবীর বিবরণ লিখুন',
    employees: 'কর্মচারী',
    summary: 'সারসংক্ষেপ',
  },
}
