export default {
  employees: {
    module: 'Employee',
    management: 'Employee Management',
    performance: 'Employee Performance',
    add: 'Add Employee',
    edit: 'Edit Employee',
    view: 'View Employee Details',
    create: 'Create Employee',

    personal_info: 'Personal Info',
    access_status: 'Access & Status',
    credentials: 'Credentials',

    username: 'Username',
    department: 'Department',
    assign_roles: 'Assign Roles',
    show_ats_summary: 'Show ATS Summary',
    manager_approval: 'Manager Approval',
    send_credentials: 'Sent Credentials',
    upload_document: 'Upload document (Optional)',
    generate_password: 'Generate Password',
    auto_generate_password: 'Auto-generate password',
    select: 'Select',

    table_view: 'Table View',
    grid_view: 'Grid View',
    empty: 'No employees found',
    empty_hint: 'Try adjusting your filters or adding a new employee.',
    tasks_count: '{count} Tasks',
    pending_count: '{count} Pending',

    credentials_copied: 'Credentials copied!',
    credentials_copy_failed: 'Failed to copy credentials. Please try manually.',
    credentials_for: 'Credentials for {name}:',
    login_url: 'Login URL',

    not_provided: 'Not Provided',
    na: 'N/A',
    employee_id_label: 'Employee ID',
    employee_name: 'Employee Name',
    points: 'Points',

    placeholder_name: 'Eg: Abdul Alim',
    placeholder_username: 'Eg: johndoe',
    placeholder_email: "Eg: rabit{'@'}example.com",
    placeholder_phone: 'Eg: +1234567890',
  },

  departments: {
    module: 'Department',
    management: 'Department Management',
    add: 'Add Department',
    edit: 'Edit Department',
    view: 'View Department Details',
    create: 'Create Department',
    name: 'Name',
    placeholder_name: 'Enter Department name',
    department_id: 'Department ID',
    employees_assigned: '{count} employee assigned | {count} employees assigned',
    employees: 'Employees',
  },

  designations: {
    module: 'Designation',
    management: 'Designation Management',
    add: 'Add Designation',
    edit: 'Edit Designation',
    view: 'View Designation Details',
    delete: 'Delete Designation',
    delete_confirm: 'Are you sure you want to delete this Designation?',
    bulk_delete_confirm: 'Are you sure to delete selected records?',
    info: 'Designation Info',
    name: 'Name',
    description: 'Description',
    placeholder_name: 'Eg: Manager',
    placeholder_description: 'Enter designation description',
    employees: 'Employees',
    summary: 'Summary',
  },
}
