<?php

namespace App\Modules\Application\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Application\Models\Application;
use App\Modules\JobList\Models\JobList;
use App\Modules\Agent\Models\Agent;

class ApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $jobListIds = JobList::pluck('id')->toArray();
        $jobListId1 = JobList::where('job_code', 'JOB-006')->first()->id;
        $jobListId2 = JobList::where('job_code', 'JOB-007')->first()->id;
        $jobListId3 = JobList::where('job_code', 'JOB-008')->first()->id;
        $candidateTest = JobList::where('job_code', 'JOB-004')->first()->id;
        $jobListIds = JobList::pluck('id')->toArray();
        $agentIds = Agent::pluck('id')->toArray();

        $items = [
            [
                'sur_name' => 'Smith',
                'given_name' => 'John',
                'date_of_birth' => '1990-05-14',
                'sex' => 'Male',
                'nationality' => 'American',
                'bd_exp' => '5 Years',
                'overseas_exp' => '2 Years',
                'language' => 'English',
                'mobile' => '1234567890',
                'height' => '180 cm',
                'weight' => '75 kg',
                'email' => 'john.smith@example.com',
                'application_id' => 'APP-001',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID123456',
                'driving_license_no' => 'DL123456',
                'passport_path' => null,
                'passport_link' => null,
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2018-01-01',
                'date_of_expiry' => '2028-01-01',
                'passport_no' => 'P1234567',
                'place_of_birth' => 'New York',
                'resume_link' => null,
                'resume_path' => null,
                'remarks' => null,
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Doe',
                'given_name' => 'Jane',
                'date_of_birth' => '1992-09-23',
                'sex' => 'Female',
                'nationality' => 'Canadian',
                'bd_exp' => '3 Years',
                'overseas_exp' => null,
                'language' => 'English, French',
                'mobile' => '0987654321',
                'email' => 'jane.doe@example.com',
                'application_id' => 'APP-002',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID654321',
                'driving_license_no' => 'DL654321',
                'passport_path' => null,
                'passport_link' => null,
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2019-03-15',
                'height' => '165 cm',
                'weight' => '60 kg',
                'date_of_expiry' => '2029-03-15',
                'passport_no' => 'P7654321',
                'place_of_birth' => 'Toronto',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Strong candidate',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 1,
                'qualification_id' => 3,
            ],
            [
                'sur_name' => 'Khan',
                'given_name' => 'Ali',
                'date_of_birth' => '1988-12-05',
                'sex' => 'Male',
                'nationality' => 'Pakistani',
                'bd_exp' => '7 Years',
                'overseas_exp' => '1 Year',
                'language' => 'English, Urdu',
                'mobile' => '0112233445',
                'whatsapp_no' => '0112233445',
                'email' => 'ali.khan@example.com',
                'application_id' => 'APP-003',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID987654',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_path' => null,
                'passport_link' => null,
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2020-06-10',
                'date_of_expiry' => '2030-06-10',
                'passport_no' => 'P9876543',
                'place_of_birth' => 'Lahore',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Does not meet requirements',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 3,
                'qualification_id' => 2,
            ],
            [
                'sur_name' => 'Patel',
                'given_name' => 'Rina',
                'date_of_birth' => '1995-07-19',
                'sex' => 'Female',
                'nationality' => 'Indian',
                'bd_exp' => '4 Years',
                'overseas_exp' => '1 Year',
                'language' => 'English, Hindi',
                'mobile' => '0223344556',
                'whatsapp_no' => '0223344556',
                'email' => 'rina.patel@example.com',
                'application_id' => 'APP-004',
                'height' => '180 cm',
                'weight' => '75 kg',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID112233',
                'passport_path' => null,
                'passport_link' => null,
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2021-02-05',
                'date_of_expiry' => '2031-02-05',
                'passport_no' => 'P1122334',
                'place_of_birth' => 'Mumbai',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => null,
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 4,
                'qualification_id' => 1,
            ],
            [
                'sur_name' => 'Nguyen',
                'given_name' => 'Minh',
                'date_of_birth' => '1991-11-30',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => null,
                'language' => 'English, Vietnamese',
                'mobile' => '0334455667',
                'whatsapp_no' => '0334455667',
                'email' => 'minh.nguyen@example.com',
                'application_id' => 'APP-005',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID445566',
                'passport_path' => null,
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_link' => null,
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2017-08-20',
                'date_of_expiry' => '2027-08-20',
                'passport_no' => 'P44515667',
                'place_of_birth' => 'Hanoi',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Excellent experience',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Sagor',
                'given_name' => 'Ahmed',
                'date_of_birth' => '1991-11-30',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => null,
                'language' => 'English, Vietnamese',
                'mobile' => '0334455667',
                'whatsapp_no' => '0334455667',
                'email' => 'minh.nguyen@example.com',
                'application_id' => 'APP-006',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID445566',
                'passport_path' => null,
                'passport_link' => null,
                'height' => '180 cm',
                'weight' => '75 kg',
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2017-08-20',
                'date_of_expiry' => '2027-08-20',
                'passport_no' => 'P445564567',
                'place_of_birth' => 'Hanoi',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Excellent experience',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Siam',
                'given_name' => 'Hasan',
                'date_of_birth' => '1991-11-30',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => null,
                'language' => 'English, Vietnamese',
                'mobile' => '0334455667',
                'whatsapp_no' => '0334455667',
                'email' => 'minh.nguyen@example.com',
                'application_id' => 'APP-007',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID445566',
                'passport_path' => null,
                'passport_link' => null,
                'height' => '180 cm',
                'weight' => '75 kg',
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2017-08-20',
                'date_of_expiry' => '2027-08-20',
                'passport_no' => 'P44556467',
                'place_of_birth' => 'Hanoi',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Excellent experience',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 5,
                'qualification_id' => 6,
            ],
            [
                'sur_name' => 'Rahim',
                'given_name' => 'Ahmed',
                'date_of_birth' => '1991-11-30',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => null,
                'language' => 'English, Vietnamese',
                'mobile' => '0334455667',
                'whatsapp_no' => '0334455667',
                'email' => 'minh.nguyen@example.com',
                'application_id' => 'APP-008',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID445566',
                'passport_path' => null,
                'passport_link' => null,
                'height' => '180 cm',
                'weight' => '75 kg',
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2017-08-20',
                'date_of_expiry' => '2027-08-20',
                'passport_no' => 'P443555667',
                'place_of_birth' => 'Hanoi',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Excellent experience',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 5,
                'qualification_id' => 6,
            ],
            [
                'sur_name' => 'Mijan',
                'given_name' => 'Ahmed',
                'date_of_birth' => '1991-11-30',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => null,
                'language' => 'English, Vietnamese',
                'mobile' => '0334455667',
                'whatsapp_no' => '0334455667',
                'email' => 'minh.nguyen@example.com',
                'application_id' => 'APP-009',
                'nid_path' => null,
                'nid_link' => null,
                'nid_no' => 'NID445566',
                'passport_path' => null,
                'passport_link' => null,
                'height' => '180 cm',
                'weight' => '75 kg',
                'offer_letter_link' => null,
                'offer_letter_path' => null,
                'date_of_issue' => '2017-08-20',
                'date_of_expiry' => '2027-08-20',
                'passport_no' => 'P42455667',
                'place_of_birth' => 'Hanoi',
                'resume_link' => null,
                'resume_path' => null,

                'remarks' => 'Excellent experience',
                'created_by' => 1,
                'job_list_id' => $jobListIds[array_rand($jobListIds)],
                'subject_id' => 2,
                'qualification_id' => 4,
            ],

            // newly seeded
            /*
    |--------------------------------------------------------------------------
    | JobList[0] → 5 Applications (APP-010 → APP-014)
    |--------------------------------------------------------------------------
    */
            [
                'sur_name' => 'Tanvir',
                'given_name' => 'Hossain',
                'date_of_birth' => '1992-04-12',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '5 Years',
                'overseas_exp' => null,
                'language' => 'English',
                'mobile' => '01720000010',
                'whatsapp_no' => '01720000010',
                'email' => 'tanvir.h@app.com',
                'application_id' => 'APP-010',
                'nid_no' => 'NID5010',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5010',
                'date_of_issue' => '2018-03-10',
                'date_of_expiry' => '2028-03-10',
                'place_of_birth' => 'Hanoi',
                'remarks' => 'Skilled technician',
                'created_by' => 1,
                'job_list_id' => $jobListId1,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Rashed',
                'given_name' => 'Mahmud',
                'date_of_birth' => '1990-09-22',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '7 Years',
                'overseas_exp' => '2 Years',
                'language' => 'English',
                'mobile' => '01720000011',
                'whatsapp_no' => '01720000011',
                'email' => 'rashed.m@app.com',
                'application_id' => 'APP-011',
                'nid_no' => 'NID5011',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5011',
                'date_of_issue' => '2017-01-05',
                'date_of_expiry' => '2027-01-05',
                'place_of_birth' => 'Da Nang',
                'remarks' => 'Overseas experience',
                'created_by' => 1,
                'job_list_id' => $jobListId1,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Imran',
                'given_name' => 'Kabir',
                'date_of_birth' => '1993-07-18',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '4 Years',
                'overseas_exp' => null,
                'language' => 'English',
                'mobile' => '01720000012',
                'whatsapp_no' => '01720000012',
                'email' => 'imran.k@app.com',
                'application_id' => 'APP-012',
                'nid_no' => 'NID5012',
                'passport_no' => 'P5012',
                'date_of_issue' => '2019-05-20',
                'date_of_expiry' => '2029-05-20',
                'place_of_birth' => 'Hue',
                'remarks' => 'Fast learner',
                'created_by' => 1,
                'job_list_id' => $jobListId1,
                'subject_id' => 6,
                'qualification_id' => 7,
            ],
            [
                'sur_name' => 'Shakil',
                'given_name' => 'Ahmed',
                'date_of_birth' => '1989-12-01',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '8 Years',
                'overseas_exp' => '3 Years',
                'language' => 'English',
                'height' => '180 cm',
                'weight' => '75 kg',
                'mobile' => '01720000013',
                'whatsapp_no' => '01720000013',
                'email' => 'shakil.a@app.com',
                'application_id' => 'APP-013',
                'nid_no' => 'NID5013',
                'passport_no' => 'P5013',
                'date_of_issue' => '2016-11-11',
                'date_of_expiry' => '2026-11-11',
                'place_of_birth' => 'Can Tho',
                'remarks' => 'Senior worker',
                'created_by' => 1,
                'job_list_id' => $jobListId1,
                'subject_id' => 6,
                'qualification_id' => 7,
            ],
            [
                'sur_name' => 'Mamun',
                'given_name' => 'Khan',
                'date_of_birth' => '1994-02-08',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '3 Years',
                'overseas_exp' => null,
                'height' => '180 cm',
                'weight' => '75 kg',
                'language' => 'English',
                'mobile' => '01720000014',
                'whatsapp_no' => '01720000014',
                'email' => 'mamun.k@app.com',
                'application_id' => 'APP-014',
                'nid_no' => 'NID5014',
                'passport_no' => 'P5014',
                'date_of_issue' => '2020-02-02',
                'date_of_expiry' => '2030-02-02',
                'place_of_birth' => 'Hanoi',
                'remarks' => 'Junior engineer',
                'created_by' => 1,
                'job_list_id' => $jobListId1,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],

            /*
            |--------------------------------------------------------------------------
            | JobList[1] → 3 Applications (APP-015 → APP-017)
            |--------------------------------------------------------------------------
            */
            [
                'sur_name' => 'Arif',
                'given_name' => 'Hasan',
                'date_of_birth' => '1991-06-10',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => null,
                'language' => 'English',
                'mobile' => '01720000015',
                'whatsapp_no' => '01720000015',
                'email' => 'arif.h@app.com',
                'application_id' => 'APP-015',
                'nid_no' => 'NID5015',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5015',
                'date_of_issue' => '2017-09-01',
                'date_of_expiry' => '2027-09-01',
                'place_of_birth' => 'Hai Phong',
                'remarks' => 'Reliable worker',
                'created_by' => 1,
                'job_list_id' => $jobListId2,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Jahid',
                'given_name' => 'Islam',
                'date_of_birth' => '1993-03-15',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '4 Years',
                'overseas_exp' => null,
                'language' => 'English',
                'mobile' => '01720000016',
                'whatsapp_no' => '01720000016',
                'email' => 'jahid.i@app.com',
                'application_id' => 'APP-016',
                'height' => '180 cm',
                'weight' => '75 kg',
                'nid_no' => 'NID5016',
                'passport_no' => 'P5016',
                'date_of_issue' => '2019-08-08',
                'date_of_expiry' => '2029-08-08',
                'place_of_birth' => 'Hue',
                'remarks' => 'Quick processing',
                'created_by' => 1,
                'job_list_id' => $jobListId2,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Nayeem',
                'given_name' => 'Uddin',
                'date_of_birth' => '1990-01-25',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '7 Years',
                'overseas_exp' => '1 Year',
                'language' => 'English',
                'height' => '180 cm',
                'weight' => '75 kg',
                'mobile' => '01720000017',
                'whatsapp_no' => '01720000017',
                'email' => 'nayeem.u@app.com',
                'application_id' => 'APP-017',
                'nid_no' => 'NID5017',
                'passport_no' => 'P5017',
                'date_of_issue' => '2016-04-14',
                'date_of_expiry' => '2026-04-14',
                'place_of_birth' => 'Hanoi',
                'remarks' => 'Strong profile',
                'created_by' => 1,
                'job_list_id' => $jobListId2,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],

            /*
            |--------------------------------------------------------------------------
            | JobList[2] → 2 Applications (APP-018 → APP-019)
            |--------------------------------------------------------------------------
            */
            [
                'sur_name' => 'Sabbir',
                'given_name' => 'Rahman',
                'date_of_birth' => '1994-10-10',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '3 Years',
                'overseas_exp' => null,
                'language' => 'English',
                'mobile' => '01720000018',
                'whatsapp_no' => '01720000018',
                'email' => 'sabbir.r@app.com',
                'application_id' => 'APP-018',
                'nid_no' => 'NID5018',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5018',
                'date_of_issue' => '2020-10-10',
                'date_of_expiry' => '2030-10-10',
                'place_of_birth' => 'Da Nang',
                'remarks' => 'New candidate',
                'created_by' => 1,
                'job_list_id' => $jobListId3,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Faruk',
                'given_name' => 'Haque',
                'date_of_birth' => '1988-05-05',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '9 Years',
                'overseas_exp' => '4 Years',
                'language' => 'English',
                'mobile' => '01720000019',
                'whatsapp_no' => '01720000019',
                'email' => 'faruk.h@app.com',
                'application_id' => 'APP-019',
                'nid_no' => 'NID5019',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5019',
                'date_of_issue' => '2015-05-05',
                'date_of_expiry' => '2025-05-05',
                'place_of_birth' => 'Ho Chi Minh',
                'remarks' => 'Very experienced',
                'created_by' => 1,
                'job_list_id' => $jobListId3,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            // for testing candidate bill
            [
                'sur_name' => 'MD Anisul Haque',
                'given_name' => 'Haque',
                'date_of_birth' => '1988-05-05',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '9 Years',
                'overseas_exp' => '4 Years',
                'language' => 'English',
                'mobile' => '01720003419',
                'whatsapp_no' => '01720003419',
                'email' => 'farudk.h@app.com',
                'application_id' => 'APP-020',
                'height' => '180 cm',
                'weight' => '75 kg',
                'nid_no' => 'NID5020',
                'passport_no' => 'P5020',
                'date_of_issue' => '2015-05-05',
                'date_of_expiry' => '2025-05-05',
                'place_of_birth' => 'Ho Chi Minh',
                'remarks' => 'Very experienced',
                'created_by' => 1,
                'job_list_id' => $candidateTest,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],
            [
                'sur_name' => 'Tran Van',
                'given_name' => 'Minh',
                'date_of_birth' => '1990-03-12',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '7 Years',
                'overseas_exp' => '3 Years',
                'language' => 'English',
                'mobile' => '01720003420',
                'whatsapp_no' => '01720003420',
                'email' => 'minh.tran@app.com',
                'application_id' => 'APP-021',
                'nid_no' => 'NID5021',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5021',
                'date_of_issue' => '2016-03-12',
                'date_of_expiry' => '2026-03-12',
                'place_of_birth' => 'Hanoi',
                'remarks' => 'Skilled electrician',
                'created_by' => 1,
                'job_list_id' => $candidateTest,
                'subject_id' => 2,
                'qualification_id' => 4,

            ],

            [
                'sur_name' => 'Nguyen Thi',
                'given_name' => 'Lan',
                'date_of_birth' => '1992-07-18',
                'sex' => 'Female',
                'nationality' => 'Vietnamese',
                'bd_exp' => '5 Years',
                'overseas_exp' => '2 Years',
                'language' => 'English',
                'mobile' => '01720003421',
                'whatsapp_no' => '01720003421',
                'email' => 'lan.nguyen@app.com',
                'application_id' => 'APP-022',
                'nid_no' => 'NID5022',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5022',
                'date_of_issue' => '2017-07-18',
                'date_of_expiry' => '2027-07-18',
                'place_of_birth' => 'Da Nang',
                'remarks' => 'Experienced nurse',
                'created_by' => 1,
                'job_list_id' => $candidateTest,
                'subject_id' => 6,
                'qualification_id' => 7,
            ],

            [
                'sur_name' => 'Le Hoang',
                'given_name' => 'Nam',
                'date_of_birth' => '1987-11-09',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '10 Years',
                'overseas_exp' => '5 Years',
                'language' => 'English',
                'mobile' => '01720003422',
                'whatsapp_no' => '01720003422',
                'email' => 'nam.le@app.com',
                'application_id' => 'APP-023',
                'nid_no' => 'NID5023',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5023',
                'date_of_issue' => '2014-11-09',
                'date_of_expiry' => '2024-11-09',
                'place_of_birth' => 'Can Tho',
                'remarks' => 'Senior mechanic',
                'created_by' => 1,
                'job_list_id' => $candidateTest,
                'subject_id' => 2,
                'qualification_id' => 4,

            ],

            [
                'sur_name' => 'Pham Quoc',
                'given_name' => 'Huy',
                'date_of_birth' => '1991-01-25',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '6 Years',
                'overseas_exp' => '3 Years',
                'language' => 'English',
                'mobile' => '01720003423',
                'whatsapp_no' => '01720003423',
                'height' => '180 cm',
                'weight' => '75 kg',
                'email' => 'huy.pham@app.com',
                'application_id' => 'APP-024',
                'nid_no' => 'NID5024',
                'passport_no' => 'P5024',
                'date_of_issue' => '2018-01-25',
                'date_of_expiry' => '2028-01-25',
                'place_of_birth' => 'Hue',
                'remarks' => 'Hardworking worker',
                'created_by' => 1,
                'job_list_id' => $candidateTest,
                'subject_id' => 2,
                'qualification_id' => 4,
            ],

            [
                'sur_name' => 'Vo Thanh',
                'given_name' => 'Binh',
                'date_of_birth' => '1989-09-14',
                'sex' => 'Male',
                'nationality' => 'Vietnamese',
                'bd_exp' => '8 Years',
                'overseas_exp' => '4 Years',
                'language' => 'English',
                'mobile' => '01720003424',
                'whatsapp_no' => '01720003424',
                'email' => 'binh.vo@app.com',
                'application_id' => 'APP-025',
                'nid_no' => 'NID5025',
                'height' => '180 cm',
                'weight' => '75 kg',
                'passport_no' => 'P5025',
                'date_of_issue' => '2015-09-14',
                'date_of_expiry' => '2025-09-14',
                'place_of_birth' => 'Nha Trang',
                'remarks' => 'Professional welder',
                'created_by' => 1,
                'job_list_id' => $candidateTest,
                'subject_id' => 6,
                'qualification_id' => 7,

            ],



        ];

        foreach ($items as $item) {
            $item['agent_id'] = $agentIds[array_rand($agentIds)];
            Application::create($item);
        }


    }
}
