<?php

namespace App\Modules\Application\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Application\Models\Transaction;
use App\Modules\Application\Models\Application;
use App\Modules\Client\Models\Client;

class TransactionSeeder extends Seeder
{
    public function run(): void
    {
        $applicationIds = Application::pluck('id')->toArray();


        $items = [
            [
                'transaction_id' => 'CX22GH2292',
                'bill_no'        => 'BILL-001',
                'total_amount'   => 5000,
                'paid_amount'    => 2000,
                'total_amount_usd'   => 5000,
                'paid_amount_usd'    => 2000,
                'discount_amount' => 0,
                'payment_method' => 'bkash',
                'status'         => 'due',
                'payment_date'   => now()->toDateString(),
                'payment_time'   => now()->toTimeString(),
                'remarks'        => 'Partial payment received',
                'created_by'     => 1,
                'application_id' => $applicationIds[array_rand($applicationIds)],
            ],
            [
                'transaction_id' => 'CX22GH2293',
                'bill_no'        => 'BILL-002',
                'total_amount'   => 8000,
                'paid_amount'    => 8000,
                'total_amount_usd'   => 120,
                'paid_amount_usd'    => 40,
                'discount_amount' => 500,
                'payment_method' => 'bank',
                'status'         => 'paid',
                'payment_date'   => now()->toDateString(),
                'payment_time'   => now()->toTimeString(),
                'remarks'        => null,
                'created_by'     => 1,
                'application_id' => $applicationIds[array_rand($applicationIds)],
            ],
            [
                'transaction_id' => 'CX22GH2294',
                'bill_no'        => 'BILL-003',
                'total_amount'   => 12000,
                'paid_amount'    => 0,
                'total_amount_usd'   => 120,
                'paid_amount_usd'    => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status'         => 'draft',
                'payment_date'   => now()->toDateString(),
                'payment_time'   => now()->toTimeString(),
                'remarks'        => 'Invoice created',
                'created_by'     => 1,
                'application_id' => $applicationIds[array_rand($applicationIds)],
            ],
            [
                'transaction_id' => 'CX22GH2295',
                'bill_no'        => 'BILL-004',
                'total_amount'   => 15000,
                'paid_amount'    => 15000,
                'total_amount_usd'   => 150,
                'paid_amount_usd'    => 150,
                'discount_amount' => 0,
                'payment_method' => 'bkash',
                'status'         => 'bill-generated',
                'payment_date'   => now()->toDateString(),
                'payment_time'   => now()->toTimeString(),
                'remarks'        => 'Paid in full',
                'created_by'     => 1,
                'application_id' => $applicationIds[array_rand($applicationIds)],
            ],
            [
                'transaction_id' => 'CX22GH2296',
                'bill_no'        => 'BILL-005',
                'total_amount'   => 6000,
                'paid_amount'    => 3000,
                'total_amount_usd'   => 60,
                'paid_amount_usd'    => 30,
                'discount_amount' => 0,
                'payment_method' => 'bkash',
                'status'         => 'due',
                'payment_date'   => now()->toDateString(),
                'payment_time'   => now()->toTimeString(),
                'remarks'        => 'Advance payment',
                'created_by'     => 1,
                'application_id' => $applicationIds[array_rand($applicationIds)],
            ],
            // newly seeded
            [
                'transaction_id' => 'CX22GH2297',
                'bill_no' => NULL,
                'total_amount' => 10000,
                'paid_amount' => 0,
                'total_amount_usd' => 100,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-010')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2298',
                'bill_no' => NULL,
                'total_amount' => 12000,
                'paid_amount' => 0,
                'total_amount_usd' => 120,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-011')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2299',
                'bill_no' => NULL,
                'total_amount' => 9000,
                'paid_amount' => 0,
                'total_amount_usd' => 90,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-012')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2300',
                'bill_no' => NULL,
                'total_amount' => 15000,
                'paid_amount' => 0,
                'total_amount_usd' => 150,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-013')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2301',
                'bill_no' => NULL,
                'total_amount' => 11000,
                'paid_amount' => 0,
                'total_amount_usd' => 110,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-014')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2302',
                'bill_no' => NULL,
                'total_amount' => 13000,
                'paid_amount' => 0,
                'total_amount_usd' => 130,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-015')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2303',
                'bill_no' => NULL,
                'total_amount' => 8000,
                'paid_amount' => 0,
                'total_amount_usd' => 80,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,

                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-016')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2304',
                'bill_no' => NULL,
                'total_amount' => 14000,
                'paid_amount' => 0,
                'total_amount_usd' => 140,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-017')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2305',
                'bill_no' => NULL,
                'total_amount' => 9500,
                'paid_amount' => 0,
                'total_amount_usd' => 95,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-018')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2306',
                'bill_no' => NULL,
                'total_amount' => 16000,
                'paid_amount' => 0,
                'total_amount_usd' => 160,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'application_id' => Application::where('application_id', 'APP-019')->first()->id,
                'created_by' => 1,
            ],
            // for testing job payer candidate  transactions
            [
                'transaction_id' => 'CX22GH2307',
                'bill_no' => 'BILL-007',
                'total_amount' => 16000,
                'paid_amount' => 0,
                'total_amount_usd' => 160,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'client bill generated',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-020')->first()->id,
            ],
            [
                'transaction_id' => 'CX22GH2308',
                'bill_no' => 'BILL-008',
                'total_amount' => 18000,
                'paid_amount' => 0,
                'total_amount_usd' => 180,
                'paid_amount_usd' => 0,
                'discount_amount' => 1000,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'partial payment received',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-021')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2309',
                'bill_no' => 'BILL-009',
                'total_amount' => 20000,
                'paid_amount' => 0,
                'total_amount_usd' => 200,
                'paid_amount_usd' => 0,
                'discount_amount' => 0,
                'payment_method' => 'cash',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'full payment completed',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-022')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2310',
                'bill_no' => 'BILL-010',
                'total_amount' => 15000,
                'paid_amount' => 0,
                'total_amount_usd' => 150,
                'paid_amount_usd' => 0,
                'discount_amount' => 500,
                'payment_method' => 'cash',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'second installment pending',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-023')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2311',
                'bill_no' => 'BILL-011',
                'total_amount' => 22000,
                'paid_amount' => 0,
                'total_amount_usd' => 220,
                'paid_amount_usd' => 0,
                'discount_amount' => 2000,
                'payment_method' => 'bank',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'discount applied, awaiting payment',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-024')->first()->id,
            ],

            [
                'transaction_id' => 'CX22GH2312',
                'bill_no' => 'BILL-012',
                'total_amount' => 25000,
                'paid_amount' => 0,
                'total_amount_usd' => 250,
                'paid_amount_usd' => 20,
                'discount_amount' => 1000,
                'payment_method' => 'pending',
                'status' => 'bill-generated',
                'payment_date' => now()->toDateString(),
                'payment_time' => now()->toTimeString(),
                'remarks' => 'bill generated successfully',
                'created_by' => 1,
                'application_id' => Application::where('application_id', 'APP-025')->first()->id,
            ],

        ];

        foreach ($items as $item) {
            Transaction::create($item);
        }
    }
}
